
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Department'
export type * from './models/RecruitmentTimeline'
export type * from './models/Attendance'
export type * from './models/Division'
export type * from './models/SubDivision'
export type * from './models/Profile'
export type * from './models/SubmissionVerification'
export type * from './models/Payment'
export type * from './models/Exam'
export type * from './models/Question'
export type * from './models/Choice'
export type * from './models/ExamAttempt'
export type * from './models/ExamAnswer'
export type * from './models/LearningModule'
export type * from './models/Assignment'
export type * from './models/AssignmentSubmission'
export type * from './commonInputTypes'