
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Department: 'Department',
  RecruitmentTimeline: 'RecruitmentTimeline',
  Attendance: 'Attendance',
  Division: 'Division',
  SubDivision: 'SubDivision',
  Profile: 'Profile',
  SubmissionVerification: 'SubmissionVerification',
  Payment: 'Payment',
  Exam: 'Exam',
  Question: 'Question',
  Choice: 'Choice',
  ExamAttempt: 'ExamAttempt',
  ExamAnswer: 'ExamAnswer',
  LearningModule: 'LearningModule',
  Assignment: 'Assignment',
  AssignmentSubmission: 'AssignmentSubmission'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DepartmentScalarFieldEnum = (typeof DepartmentScalarFieldEnum)[keyof typeof DepartmentScalarFieldEnum]


export const RecruitmentTimelineScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  startAt: 'startAt',
  endAt: 'endAt',
  orderIndex: 'orderIndex',
  attendancePasscode: 'attendancePasscode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecruitmentTimelineScalarFieldEnum = (typeof RecruitmentTimelineScalarFieldEnum)[keyof typeof RecruitmentTimelineScalarFieldEnum]


export const AttendanceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  timelineId: 'timelineId',
  checkInTime: 'checkInTime',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AttendanceScalarFieldEnum = (typeof AttendanceScalarFieldEnum)[keyof typeof AttendanceScalarFieldEnum]


export const DivisionScalarFieldEnum = {
  id: 'id',
  departmentId: 'departmentId',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DivisionScalarFieldEnum = (typeof DivisionScalarFieldEnum)[keyof typeof DivisionScalarFieldEnum]


export const SubDivisionScalarFieldEnum = {
  id: 'id',
  divisionId: 'divisionId',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubDivisionScalarFieldEnum = (typeof SubDivisionScalarFieldEnum)[keyof typeof SubDivisionScalarFieldEnum]


export const ProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  nickName: 'nickName',
  nim: 'nim',
  whatsappNumber: 'whatsappNumber',
  studyProgram: 'studyProgram',
  departmentId: 'departmentId',
  divisionId: 'divisionId',
  subDivisionId: 'subDivisionId',
  avatarUrl: 'avatarUrl',
  rejectionReason: 'rejectionReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const SubmissionVerificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  krsScanUrl: 'krsScanUrl',
  formalPhotoUrl: 'formalPhotoUrl',
  instagramProofUrl: 'instagramProofUrl',
  instagramMarketingProofUrl: 'instagramMarketingProofUrl',
  twibbonLink: 'twibbonLink',
  status: 'status',
  rejectionReason: 'rejectionReason',
  reviewedByAdminId: 'reviewedByAdminId',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubmissionVerificationScalarFieldEnum = (typeof SubmissionVerificationScalarFieldEnum)[keyof typeof SubmissionVerificationScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  provider: 'provider',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  externalPaymentId: 'externalPaymentId',
  paymentUrl: 'paymentUrl',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const ExamScalarFieldEnum = {
  id: 'id',
  subDivisionId: 'subDivisionId',
  title: 'title',
  description: 'description',
  durationMinutes: 'durationMinutes',
  maxAttempts: 'maxAttempts',
  startAt: 'startAt',
  endAt: 'endAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExamScalarFieldEnum = (typeof ExamScalarFieldEnum)[keyof typeof ExamScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  examId: 'examId',
  type: 'type',
  prompt: 'prompt',
  correctTextAnswer: 'correctTextAnswer',
  points: 'points',
  orderIndex: 'orderIndex',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const ChoiceScalarFieldEnum = {
  id: 'id',
  questionId: 'questionId',
  label: 'label',
  isCorrect: 'isCorrect',
  orderIndex: 'orderIndex'
} as const

export type ChoiceScalarFieldEnum = (typeof ChoiceScalarFieldEnum)[keyof typeof ChoiceScalarFieldEnum]


export const ExamAttemptScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  examId: 'examId',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt',
  totalQuestions: 'totalQuestions',
  score: 'score',
  correctCount: 'correctCount',
  wrongCount: 'wrongCount',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExamAttemptScalarFieldEnum = (typeof ExamAttemptScalarFieldEnum)[keyof typeof ExamAttemptScalarFieldEnum]


export const ExamAnswerScalarFieldEnum = {
  id: 'id',
  attemptId: 'attemptId',
  questionId: 'questionId',
  chosenChoiceId: 'chosenChoiceId',
  textAnswer: 'textAnswer',
  isCorrect: 'isCorrect',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExamAnswerScalarFieldEnum = (typeof ExamAnswerScalarFieldEnum)[keyof typeof ExamAnswerScalarFieldEnum]


export const LearningModuleScalarFieldEnum = {
  id: 'id',
  subDivisionId: 'subDivisionId',
  title: 'title',
  description: 'description',
  fileUrl: 'fileUrl',
  createdByAdminId: 'createdByAdminId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LearningModuleScalarFieldEnum = (typeof LearningModuleScalarFieldEnum)[keyof typeof LearningModuleScalarFieldEnum]


export const AssignmentScalarFieldEnum = {
  id: 'id',
  subDivisionId: 'subDivisionId',
  title: 'title',
  description: 'description',
  fileUrl: 'fileUrl',
  dueAt: 'dueAt',
  createdByAdminId: 'createdByAdminId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssignmentScalarFieldEnum = (typeof AssignmentScalarFieldEnum)[keyof typeof AssignmentScalarFieldEnum]


export const AssignmentSubmissionScalarFieldEnum = {
  id: 'id',
  assignmentId: 'assignmentId',
  userId: 'userId',
  fileUrl: 'fileUrl',
  submittedAt: 'submittedAt',
  score: 'score',
  feedback: 'feedback',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssignmentSubmissionScalarFieldEnum = (typeof AssignmentSubmissionScalarFieldEnum)[keyof typeof AssignmentSubmissionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

