
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LearningModule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LearningModule
 * 
 */
export type LearningModuleModel = runtime.Types.Result.DefaultSelection<Prisma.$LearningModulePayload>

export type AggregateLearningModule = {
  _count: LearningModuleCountAggregateOutputType | null
  _min: LearningModuleMinAggregateOutputType | null
  _max: LearningModuleMaxAggregateOutputType | null
}

export type LearningModuleMinAggregateOutputType = {
  id: string | null
  subDivisionId: string | null
  title: string | null
  description: string | null
  fileUrl: string | null
  createdByAdminId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LearningModuleMaxAggregateOutputType = {
  id: string | null
  subDivisionId: string | null
  title: string | null
  description: string | null
  fileUrl: string | null
  createdByAdminId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LearningModuleCountAggregateOutputType = {
  id: number
  subDivisionId: number
  title: number
  description: number
  fileUrl: number
  createdByAdminId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LearningModuleMinAggregateInputType = {
  id?: true
  subDivisionId?: true
  title?: true
  description?: true
  fileUrl?: true
  createdByAdminId?: true
  createdAt?: true
  updatedAt?: true
}

export type LearningModuleMaxAggregateInputType = {
  id?: true
  subDivisionId?: true
  title?: true
  description?: true
  fileUrl?: true
  createdByAdminId?: true
  createdAt?: true
  updatedAt?: true
}

export type LearningModuleCountAggregateInputType = {
  id?: true
  subDivisionId?: true
  title?: true
  description?: true
  fileUrl?: true
  createdByAdminId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LearningModuleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LearningModule to aggregate.
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningModules to fetch.
   */
  orderBy?: Prisma.LearningModuleOrderByWithRelationInput | Prisma.LearningModuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LearningModuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningModules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningModules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LearningModules
  **/
  _count?: true | LearningModuleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LearningModuleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LearningModuleMaxAggregateInputType
}

export type GetLearningModuleAggregateType<T extends LearningModuleAggregateArgs> = {
      [P in keyof T & keyof AggregateLearningModule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLearningModule[P]>
    : Prisma.GetScalarType<T[P], AggregateLearningModule[P]>
}




export type LearningModuleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LearningModuleWhereInput
  orderBy?: Prisma.LearningModuleOrderByWithAggregationInput | Prisma.LearningModuleOrderByWithAggregationInput[]
  by: Prisma.LearningModuleScalarFieldEnum[] | Prisma.LearningModuleScalarFieldEnum
  having?: Prisma.LearningModuleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LearningModuleCountAggregateInputType | true
  _min?: LearningModuleMinAggregateInputType
  _max?: LearningModuleMaxAggregateInputType
}

export type LearningModuleGroupByOutputType = {
  id: string
  subDivisionId: string
  title: string
  description: string | null
  fileUrl: string
  createdByAdminId: string
  createdAt: Date
  updatedAt: Date
  _count: LearningModuleCountAggregateOutputType | null
  _min: LearningModuleMinAggregateOutputType | null
  _max: LearningModuleMaxAggregateOutputType | null
}

type GetLearningModuleGroupByPayload<T extends LearningModuleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LearningModuleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LearningModuleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LearningModuleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LearningModuleGroupByOutputType[P]>
      }
    >
  >



export type LearningModuleWhereInput = {
  AND?: Prisma.LearningModuleWhereInput | Prisma.LearningModuleWhereInput[]
  OR?: Prisma.LearningModuleWhereInput[]
  NOT?: Prisma.LearningModuleWhereInput | Prisma.LearningModuleWhereInput[]
  id?: Prisma.StringFilter<"LearningModule"> | string
  subDivisionId?: Prisma.StringFilter<"LearningModule"> | string
  title?: Prisma.StringFilter<"LearningModule"> | string
  description?: Prisma.StringNullableFilter<"LearningModule"> | string | null
  fileUrl?: Prisma.StringFilter<"LearningModule"> | string
  createdByAdminId?: Prisma.StringFilter<"LearningModule"> | string
  createdAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
  subDivision?: Prisma.XOR<Prisma.SubDivisionScalarRelationFilter, Prisma.SubDivisionWhereInput>
  createdByAdmin?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LearningModuleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  subDivisionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subDivision?: Prisma.SubDivisionOrderByWithRelationInput
  createdByAdmin?: Prisma.UserOrderByWithRelationInput
}

export type LearningModuleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LearningModuleWhereInput | Prisma.LearningModuleWhereInput[]
  OR?: Prisma.LearningModuleWhereInput[]
  NOT?: Prisma.LearningModuleWhereInput | Prisma.LearningModuleWhereInput[]
  subDivisionId?: Prisma.StringFilter<"LearningModule"> | string
  title?: Prisma.StringFilter<"LearningModule"> | string
  description?: Prisma.StringNullableFilter<"LearningModule"> | string | null
  fileUrl?: Prisma.StringFilter<"LearningModule"> | string
  createdByAdminId?: Prisma.StringFilter<"LearningModule"> | string
  createdAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
  subDivision?: Prisma.XOR<Prisma.SubDivisionScalarRelationFilter, Prisma.SubDivisionWhereInput>
  createdByAdmin?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type LearningModuleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  subDivisionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LearningModuleCountOrderByAggregateInput
  _max?: Prisma.LearningModuleMaxOrderByAggregateInput
  _min?: Prisma.LearningModuleMinOrderByAggregateInput
}

export type LearningModuleScalarWhereWithAggregatesInput = {
  AND?: Prisma.LearningModuleScalarWhereWithAggregatesInput | Prisma.LearningModuleScalarWhereWithAggregatesInput[]
  OR?: Prisma.LearningModuleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LearningModuleScalarWhereWithAggregatesInput | Prisma.LearningModuleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LearningModule"> | string
  subDivisionId?: Prisma.StringWithAggregatesFilter<"LearningModule"> | string
  title?: Prisma.StringWithAggregatesFilter<"LearningModule"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"LearningModule"> | string | null
  fileUrl?: Prisma.StringWithAggregatesFilter<"LearningModule"> | string
  createdByAdminId?: Prisma.StringWithAggregatesFilter<"LearningModule"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LearningModule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LearningModule"> | Date | string
}

export type LearningModuleCreateInput = {
  id?: string
  title: string
  description?: string | null
  fileUrl: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subDivision: Prisma.SubDivisionCreateNestedOneWithoutLearningModulesInput
  createdByAdmin: Prisma.UserCreateNestedOneWithoutCreatedModulesInput
}

export type LearningModuleUncheckedCreateInput = {
  id?: string
  subDivisionId: string
  title: string
  description?: string | null
  fileUrl: string
  createdByAdminId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subDivision?: Prisma.SubDivisionUpdateOneRequiredWithoutLearningModulesNestedInput
  createdByAdmin?: Prisma.UserUpdateOneRequiredWithoutCreatedModulesNestedInput
}

export type LearningModuleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subDivisionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdByAdminId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleCreateManyInput = {
  id?: string
  subDivisionId: string
  title: string
  description?: string | null
  fileUrl: string
  createdByAdminId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subDivisionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdByAdminId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleListRelationFilter = {
  every?: Prisma.LearningModuleWhereInput
  some?: Prisma.LearningModuleWhereInput
  none?: Prisma.LearningModuleWhereInput
}

export type LearningModuleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LearningModuleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subDivisionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningModuleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subDivisionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningModuleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subDivisionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningModuleCreateNestedManyWithoutCreatedByAdminInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput> | Prisma.LearningModuleCreateWithoutCreatedByAdminInput[] | Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput | Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput[]
  createMany?: Prisma.LearningModuleCreateManyCreatedByAdminInputEnvelope
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
}

export type LearningModuleUncheckedCreateNestedManyWithoutCreatedByAdminInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput> | Prisma.LearningModuleCreateWithoutCreatedByAdminInput[] | Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput | Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput[]
  createMany?: Prisma.LearningModuleCreateManyCreatedByAdminInputEnvelope
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
}

export type LearningModuleUpdateManyWithoutCreatedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput> | Prisma.LearningModuleCreateWithoutCreatedByAdminInput[] | Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput | Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput[]
  upsert?: Prisma.LearningModuleUpsertWithWhereUniqueWithoutCreatedByAdminInput | Prisma.LearningModuleUpsertWithWhereUniqueWithoutCreatedByAdminInput[]
  createMany?: Prisma.LearningModuleCreateManyCreatedByAdminInputEnvelope
  set?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  disconnect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  delete?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  update?: Prisma.LearningModuleUpdateWithWhereUniqueWithoutCreatedByAdminInput | Prisma.LearningModuleUpdateWithWhereUniqueWithoutCreatedByAdminInput[]
  updateMany?: Prisma.LearningModuleUpdateManyWithWhereWithoutCreatedByAdminInput | Prisma.LearningModuleUpdateManyWithWhereWithoutCreatedByAdminInput[]
  deleteMany?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
}

export type LearningModuleUncheckedUpdateManyWithoutCreatedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput> | Prisma.LearningModuleCreateWithoutCreatedByAdminInput[] | Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput | Prisma.LearningModuleCreateOrConnectWithoutCreatedByAdminInput[]
  upsert?: Prisma.LearningModuleUpsertWithWhereUniqueWithoutCreatedByAdminInput | Prisma.LearningModuleUpsertWithWhereUniqueWithoutCreatedByAdminInput[]
  createMany?: Prisma.LearningModuleCreateManyCreatedByAdminInputEnvelope
  set?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  disconnect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  delete?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  update?: Prisma.LearningModuleUpdateWithWhereUniqueWithoutCreatedByAdminInput | Prisma.LearningModuleUpdateWithWhereUniqueWithoutCreatedByAdminInput[]
  updateMany?: Prisma.LearningModuleUpdateManyWithWhereWithoutCreatedByAdminInput | Prisma.LearningModuleUpdateManyWithWhereWithoutCreatedByAdminInput[]
  deleteMany?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
}

export type LearningModuleCreateNestedManyWithoutSubDivisionInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput> | Prisma.LearningModuleCreateWithoutSubDivisionInput[] | Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput | Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput[]
  createMany?: Prisma.LearningModuleCreateManySubDivisionInputEnvelope
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
}

export type LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput> | Prisma.LearningModuleCreateWithoutSubDivisionInput[] | Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput | Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput[]
  createMany?: Prisma.LearningModuleCreateManySubDivisionInputEnvelope
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
}

export type LearningModuleUpdateManyWithoutSubDivisionNestedInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput> | Prisma.LearningModuleCreateWithoutSubDivisionInput[] | Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput | Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput[]
  upsert?: Prisma.LearningModuleUpsertWithWhereUniqueWithoutSubDivisionInput | Prisma.LearningModuleUpsertWithWhereUniqueWithoutSubDivisionInput[]
  createMany?: Prisma.LearningModuleCreateManySubDivisionInputEnvelope
  set?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  disconnect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  delete?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  update?: Prisma.LearningModuleUpdateWithWhereUniqueWithoutSubDivisionInput | Prisma.LearningModuleUpdateWithWhereUniqueWithoutSubDivisionInput[]
  updateMany?: Prisma.LearningModuleUpdateManyWithWhereWithoutSubDivisionInput | Prisma.LearningModuleUpdateManyWithWhereWithoutSubDivisionInput[]
  deleteMany?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
}

export type LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput = {
  create?: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput> | Prisma.LearningModuleCreateWithoutSubDivisionInput[] | Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput[]
  connectOrCreate?: Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput | Prisma.LearningModuleCreateOrConnectWithoutSubDivisionInput[]
  upsert?: Prisma.LearningModuleUpsertWithWhereUniqueWithoutSubDivisionInput | Prisma.LearningModuleUpsertWithWhereUniqueWithoutSubDivisionInput[]
  createMany?: Prisma.LearningModuleCreateManySubDivisionInputEnvelope
  set?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  disconnect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  delete?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  connect?: Prisma.LearningModuleWhereUniqueInput | Prisma.LearningModuleWhereUniqueInput[]
  update?: Prisma.LearningModuleUpdateWithWhereUniqueWithoutSubDivisionInput | Prisma.LearningModuleUpdateWithWhereUniqueWithoutSubDivisionInput[]
  updateMany?: Prisma.LearningModuleUpdateManyWithWhereWithoutSubDivisionInput | Prisma.LearningModuleUpdateManyWithWhereWithoutSubDivisionInput[]
  deleteMany?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
}

export type LearningModuleCreateWithoutCreatedByAdminInput = {
  id?: string
  title: string
  description?: string | null
  fileUrl: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subDivision: Prisma.SubDivisionCreateNestedOneWithoutLearningModulesInput
}

export type LearningModuleUncheckedCreateWithoutCreatedByAdminInput = {
  id?: string
  subDivisionId: string
  title: string
  description?: string | null
  fileUrl: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleCreateOrConnectWithoutCreatedByAdminInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  create: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput>
}

export type LearningModuleCreateManyCreatedByAdminInputEnvelope = {
  data: Prisma.LearningModuleCreateManyCreatedByAdminInput | Prisma.LearningModuleCreateManyCreatedByAdminInput[]
  skipDuplicates?: boolean
}

export type LearningModuleUpsertWithWhereUniqueWithoutCreatedByAdminInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  update: Prisma.XOR<Prisma.LearningModuleUpdateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedUpdateWithoutCreatedByAdminInput>
  create: Prisma.XOR<Prisma.LearningModuleCreateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedCreateWithoutCreatedByAdminInput>
}

export type LearningModuleUpdateWithWhereUniqueWithoutCreatedByAdminInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  data: Prisma.XOR<Prisma.LearningModuleUpdateWithoutCreatedByAdminInput, Prisma.LearningModuleUncheckedUpdateWithoutCreatedByAdminInput>
}

export type LearningModuleUpdateManyWithWhereWithoutCreatedByAdminInput = {
  where: Prisma.LearningModuleScalarWhereInput
  data: Prisma.XOR<Prisma.LearningModuleUpdateManyMutationInput, Prisma.LearningModuleUncheckedUpdateManyWithoutCreatedByAdminInput>
}

export type LearningModuleScalarWhereInput = {
  AND?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
  OR?: Prisma.LearningModuleScalarWhereInput[]
  NOT?: Prisma.LearningModuleScalarWhereInput | Prisma.LearningModuleScalarWhereInput[]
  id?: Prisma.StringFilter<"LearningModule"> | string
  subDivisionId?: Prisma.StringFilter<"LearningModule"> | string
  title?: Prisma.StringFilter<"LearningModule"> | string
  description?: Prisma.StringNullableFilter<"LearningModule"> | string | null
  fileUrl?: Prisma.StringFilter<"LearningModule"> | string
  createdByAdminId?: Prisma.StringFilter<"LearningModule"> | string
  createdAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LearningModule"> | Date | string
}

export type LearningModuleCreateWithoutSubDivisionInput = {
  id?: string
  title: string
  description?: string | null
  fileUrl: string
  createdAt?: Date | string
  updatedAt?: Date | string
  createdByAdmin: Prisma.UserCreateNestedOneWithoutCreatedModulesInput
}

export type LearningModuleUncheckedCreateWithoutSubDivisionInput = {
  id?: string
  title: string
  description?: string | null
  fileUrl: string
  createdByAdminId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleCreateOrConnectWithoutSubDivisionInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  create: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput>
}

export type LearningModuleCreateManySubDivisionInputEnvelope = {
  data: Prisma.LearningModuleCreateManySubDivisionInput | Prisma.LearningModuleCreateManySubDivisionInput[]
  skipDuplicates?: boolean
}

export type LearningModuleUpsertWithWhereUniqueWithoutSubDivisionInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  update: Prisma.XOR<Prisma.LearningModuleUpdateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedUpdateWithoutSubDivisionInput>
  create: Prisma.XOR<Prisma.LearningModuleCreateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedCreateWithoutSubDivisionInput>
}

export type LearningModuleUpdateWithWhereUniqueWithoutSubDivisionInput = {
  where: Prisma.LearningModuleWhereUniqueInput
  data: Prisma.XOR<Prisma.LearningModuleUpdateWithoutSubDivisionInput, Prisma.LearningModuleUncheckedUpdateWithoutSubDivisionInput>
}

export type LearningModuleUpdateManyWithWhereWithoutSubDivisionInput = {
  where: Prisma.LearningModuleScalarWhereInput
  data: Prisma.XOR<Prisma.LearningModuleUpdateManyMutationInput, Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionInput>
}

export type LearningModuleCreateManyCreatedByAdminInput = {
  id?: string
  subDivisionId: string
  title: string
  description?: string | null
  fileUrl: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleUpdateWithoutCreatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subDivision?: Prisma.SubDivisionUpdateOneRequiredWithoutLearningModulesNestedInput
}

export type LearningModuleUncheckedUpdateWithoutCreatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subDivisionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleUncheckedUpdateManyWithoutCreatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subDivisionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleCreateManySubDivisionInput = {
  id?: string
  title: string
  description?: string | null
  fileUrl: string
  createdByAdminId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningModuleUpdateWithoutSubDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdByAdmin?: Prisma.UserUpdateOneRequiredWithoutCreatedModulesNestedInput
}

export type LearningModuleUncheckedUpdateWithoutSubDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdByAdminId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningModuleUncheckedUpdateManyWithoutSubDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdByAdminId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LearningModuleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subDivisionId?: boolean
  title?: boolean
  description?: boolean
  fileUrl?: boolean
  createdByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["learningModule"]>

export type LearningModuleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subDivisionId?: boolean
  title?: boolean
  description?: boolean
  fileUrl?: boolean
  createdByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["learningModule"]>

export type LearningModuleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subDivisionId?: boolean
  title?: boolean
  description?: boolean
  fileUrl?: boolean
  createdByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["learningModule"]>

export type LearningModuleSelectScalar = {
  id?: boolean
  subDivisionId?: boolean
  title?: boolean
  description?: boolean
  fileUrl?: boolean
  createdByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LearningModuleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "subDivisionId" | "title" | "description" | "fileUrl" | "createdByAdminId" | "createdAt" | "updatedAt", ExtArgs["result"]["learningModule"]>
export type LearningModuleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LearningModuleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LearningModuleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subDivision?: boolean | Prisma.SubDivisionDefaultArgs<ExtArgs>
  createdByAdmin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LearningModulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LearningModule"
  objects: {
    subDivision: Prisma.$SubDivisionPayload<ExtArgs>
    createdByAdmin: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    subDivisionId: string
    title: string
    description: string | null
    fileUrl: string
    createdByAdminId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["learningModule"]>
  composites: {}
}

export type LearningModuleGetPayload<S extends boolean | null | undefined | LearningModuleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LearningModulePayload, S>

export type LearningModuleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LearningModuleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LearningModuleCountAggregateInputType | true
  }

export interface LearningModuleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LearningModule'], meta: { name: 'LearningModule' } }
  /**
   * Find zero or one LearningModule that matches the filter.
   * @param {LearningModuleFindUniqueArgs} args - Arguments to find a LearningModule
   * @example
   * // Get one LearningModule
   * const learningModule = await prisma.learningModule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LearningModuleFindUniqueArgs>(args: Prisma.SelectSubset<T, LearningModuleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LearningModule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LearningModuleFindUniqueOrThrowArgs} args - Arguments to find a LearningModule
   * @example
   * // Get one LearningModule
   * const learningModule = await prisma.learningModule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LearningModuleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LearningModuleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LearningModule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleFindFirstArgs} args - Arguments to find a LearningModule
   * @example
   * // Get one LearningModule
   * const learningModule = await prisma.learningModule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LearningModuleFindFirstArgs>(args?: Prisma.SelectSubset<T, LearningModuleFindFirstArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LearningModule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleFindFirstOrThrowArgs} args - Arguments to find a LearningModule
   * @example
   * // Get one LearningModule
   * const learningModule = await prisma.learningModule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LearningModuleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LearningModuleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LearningModules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LearningModules
   * const learningModules = await prisma.learningModule.findMany()
   * 
   * // Get first 10 LearningModules
   * const learningModules = await prisma.learningModule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const learningModuleWithIdOnly = await prisma.learningModule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LearningModuleFindManyArgs>(args?: Prisma.SelectSubset<T, LearningModuleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LearningModule.
   * @param {LearningModuleCreateArgs} args - Arguments to create a LearningModule.
   * @example
   * // Create one LearningModule
   * const LearningModule = await prisma.learningModule.create({
   *   data: {
   *     // ... data to create a LearningModule
   *   }
   * })
   * 
   */
  create<T extends LearningModuleCreateArgs>(args: Prisma.SelectSubset<T, LearningModuleCreateArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LearningModules.
   * @param {LearningModuleCreateManyArgs} args - Arguments to create many LearningModules.
   * @example
   * // Create many LearningModules
   * const learningModule = await prisma.learningModule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LearningModuleCreateManyArgs>(args?: Prisma.SelectSubset<T, LearningModuleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LearningModules and returns the data saved in the database.
   * @param {LearningModuleCreateManyAndReturnArgs} args - Arguments to create many LearningModules.
   * @example
   * // Create many LearningModules
   * const learningModule = await prisma.learningModule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LearningModules and only return the `id`
   * const learningModuleWithIdOnly = await prisma.learningModule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LearningModuleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LearningModuleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LearningModule.
   * @param {LearningModuleDeleteArgs} args - Arguments to delete one LearningModule.
   * @example
   * // Delete one LearningModule
   * const LearningModule = await prisma.learningModule.delete({
   *   where: {
   *     // ... filter to delete one LearningModule
   *   }
   * })
   * 
   */
  delete<T extends LearningModuleDeleteArgs>(args: Prisma.SelectSubset<T, LearningModuleDeleteArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LearningModule.
   * @param {LearningModuleUpdateArgs} args - Arguments to update one LearningModule.
   * @example
   * // Update one LearningModule
   * const learningModule = await prisma.learningModule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LearningModuleUpdateArgs>(args: Prisma.SelectSubset<T, LearningModuleUpdateArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LearningModules.
   * @param {LearningModuleDeleteManyArgs} args - Arguments to filter LearningModules to delete.
   * @example
   * // Delete a few LearningModules
   * const { count } = await prisma.learningModule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LearningModuleDeleteManyArgs>(args?: Prisma.SelectSubset<T, LearningModuleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LearningModules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LearningModules
   * const learningModule = await prisma.learningModule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LearningModuleUpdateManyArgs>(args: Prisma.SelectSubset<T, LearningModuleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LearningModules and returns the data updated in the database.
   * @param {LearningModuleUpdateManyAndReturnArgs} args - Arguments to update many LearningModules.
   * @example
   * // Update many LearningModules
   * const learningModule = await prisma.learningModule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LearningModules and only return the `id`
   * const learningModuleWithIdOnly = await prisma.learningModule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LearningModuleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LearningModuleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LearningModule.
   * @param {LearningModuleUpsertArgs} args - Arguments to update or create a LearningModule.
   * @example
   * // Update or create a LearningModule
   * const learningModule = await prisma.learningModule.upsert({
   *   create: {
   *     // ... data to create a LearningModule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LearningModule we want to update
   *   }
   * })
   */
  upsert<T extends LearningModuleUpsertArgs>(args: Prisma.SelectSubset<T, LearningModuleUpsertArgs<ExtArgs>>): Prisma.Prisma__LearningModuleClient<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LearningModules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleCountArgs} args - Arguments to filter LearningModules to count.
   * @example
   * // Count the number of LearningModules
   * const count = await prisma.learningModule.count({
   *   where: {
   *     // ... the filter for the LearningModules we want to count
   *   }
   * })
  **/
  count<T extends LearningModuleCountArgs>(
    args?: Prisma.Subset<T, LearningModuleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LearningModuleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LearningModule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LearningModuleAggregateArgs>(args: Prisma.Subset<T, LearningModuleAggregateArgs>): Prisma.PrismaPromise<GetLearningModuleAggregateType<T>>

  /**
   * Group by LearningModule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningModuleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LearningModuleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LearningModuleGroupByArgs['orderBy'] }
      : { orderBy?: LearningModuleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LearningModuleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLearningModuleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LearningModule model
 */
readonly fields: LearningModuleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LearningModule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LearningModuleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subDivision<T extends Prisma.SubDivisionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubDivisionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdByAdmin<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LearningModule model
 */
export interface LearningModuleFieldRefs {
  readonly id: Prisma.FieldRef<"LearningModule", 'String'>
  readonly subDivisionId: Prisma.FieldRef<"LearningModule", 'String'>
  readonly title: Prisma.FieldRef<"LearningModule", 'String'>
  readonly description: Prisma.FieldRef<"LearningModule", 'String'>
  readonly fileUrl: Prisma.FieldRef<"LearningModule", 'String'>
  readonly createdByAdminId: Prisma.FieldRef<"LearningModule", 'String'>
  readonly createdAt: Prisma.FieldRef<"LearningModule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LearningModule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LearningModule findUnique
 */
export type LearningModuleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter, which LearningModule to fetch.
   */
  where: Prisma.LearningModuleWhereUniqueInput
}

/**
 * LearningModule findUniqueOrThrow
 */
export type LearningModuleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter, which LearningModule to fetch.
   */
  where: Prisma.LearningModuleWhereUniqueInput
}

/**
 * LearningModule findFirst
 */
export type LearningModuleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter, which LearningModule to fetch.
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningModules to fetch.
   */
  orderBy?: Prisma.LearningModuleOrderByWithRelationInput | Prisma.LearningModuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LearningModules.
   */
  cursor?: Prisma.LearningModuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningModules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningModules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LearningModules.
   */
  distinct?: Prisma.LearningModuleScalarFieldEnum | Prisma.LearningModuleScalarFieldEnum[]
}

/**
 * LearningModule findFirstOrThrow
 */
export type LearningModuleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter, which LearningModule to fetch.
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningModules to fetch.
   */
  orderBy?: Prisma.LearningModuleOrderByWithRelationInput | Prisma.LearningModuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LearningModules.
   */
  cursor?: Prisma.LearningModuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningModules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningModules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LearningModules.
   */
  distinct?: Prisma.LearningModuleScalarFieldEnum | Prisma.LearningModuleScalarFieldEnum[]
}

/**
 * LearningModule findMany
 */
export type LearningModuleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter, which LearningModules to fetch.
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningModules to fetch.
   */
  orderBy?: Prisma.LearningModuleOrderByWithRelationInput | Prisma.LearningModuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LearningModules.
   */
  cursor?: Prisma.LearningModuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningModules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningModules.
   */
  skip?: number
  distinct?: Prisma.LearningModuleScalarFieldEnum | Prisma.LearningModuleScalarFieldEnum[]
}

/**
 * LearningModule create
 */
export type LearningModuleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * The data needed to create a LearningModule.
   */
  data: Prisma.XOR<Prisma.LearningModuleCreateInput, Prisma.LearningModuleUncheckedCreateInput>
}

/**
 * LearningModule createMany
 */
export type LearningModuleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LearningModules.
   */
  data: Prisma.LearningModuleCreateManyInput | Prisma.LearningModuleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LearningModule createManyAndReturn
 */
export type LearningModuleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * The data used to create many LearningModules.
   */
  data: Prisma.LearningModuleCreateManyInput | Prisma.LearningModuleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LearningModule update
 */
export type LearningModuleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * The data needed to update a LearningModule.
   */
  data: Prisma.XOR<Prisma.LearningModuleUpdateInput, Prisma.LearningModuleUncheckedUpdateInput>
  /**
   * Choose, which LearningModule to update.
   */
  where: Prisma.LearningModuleWhereUniqueInput
}

/**
 * LearningModule updateMany
 */
export type LearningModuleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LearningModules.
   */
  data: Prisma.XOR<Prisma.LearningModuleUpdateManyMutationInput, Prisma.LearningModuleUncheckedUpdateManyInput>
  /**
   * Filter which LearningModules to update
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * Limit how many LearningModules to update.
   */
  limit?: number
}

/**
 * LearningModule updateManyAndReturn
 */
export type LearningModuleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * The data used to update LearningModules.
   */
  data: Prisma.XOR<Prisma.LearningModuleUpdateManyMutationInput, Prisma.LearningModuleUncheckedUpdateManyInput>
  /**
   * Filter which LearningModules to update
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * Limit how many LearningModules to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LearningModule upsert
 */
export type LearningModuleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * The filter to search for the LearningModule to update in case it exists.
   */
  where: Prisma.LearningModuleWhereUniqueInput
  /**
   * In case the LearningModule found by the `where` argument doesn't exist, create a new LearningModule with this data.
   */
  create: Prisma.XOR<Prisma.LearningModuleCreateInput, Prisma.LearningModuleUncheckedCreateInput>
  /**
   * In case the LearningModule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LearningModuleUpdateInput, Prisma.LearningModuleUncheckedUpdateInput>
}

/**
 * LearningModule delete
 */
export type LearningModuleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  /**
   * Filter which LearningModule to delete.
   */
  where: Prisma.LearningModuleWhereUniqueInput
}

/**
 * LearningModule deleteMany
 */
export type LearningModuleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LearningModules to delete
   */
  where?: Prisma.LearningModuleWhereInput
  /**
   * Limit how many LearningModules to delete.
   */
  limit?: number
}

/**
 * LearningModule without action
 */
export type LearningModuleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
}
