
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProgramStudi` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProgramStudi
 * 
 */
export type ProgramStudiModel = runtime.Types.Result.DefaultSelection<Prisma.$ProgramStudiPayload>

export type AggregateProgramStudi = {
  _count: ProgramStudiCountAggregateOutputType | null
  _min: ProgramStudiMinAggregateOutputType | null
  _max: ProgramStudiMaxAggregateOutputType | null
}

export type ProgramStudiMinAggregateOutputType = {
  id: string | null
  fakultas: $Enums.Fakultas | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProgramStudiMaxAggregateOutputType = {
  id: string | null
  fakultas: $Enums.Fakultas | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProgramStudiCountAggregateOutputType = {
  id: number
  fakultas: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProgramStudiMinAggregateInputType = {
  id?: true
  fakultas?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type ProgramStudiMaxAggregateInputType = {
  id?: true
  fakultas?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type ProgramStudiCountAggregateInputType = {
  id?: true
  fakultas?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProgramStudiAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramStudi to aggregate.
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramStudis to fetch.
   */
  orderBy?: Prisma.ProgramStudiOrderByWithRelationInput | Prisma.ProgramStudiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProgramStudiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramStudis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramStudis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProgramStudis
  **/
  _count?: true | ProgramStudiCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProgramStudiMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProgramStudiMaxAggregateInputType
}

export type GetProgramStudiAggregateType<T extends ProgramStudiAggregateArgs> = {
      [P in keyof T & keyof AggregateProgramStudi]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProgramStudi[P]>
    : Prisma.GetScalarType<T[P], AggregateProgramStudi[P]>
}




export type ProgramStudiGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgramStudiWhereInput
  orderBy?: Prisma.ProgramStudiOrderByWithAggregationInput | Prisma.ProgramStudiOrderByWithAggregationInput[]
  by: Prisma.ProgramStudiScalarFieldEnum[] | Prisma.ProgramStudiScalarFieldEnum
  having?: Prisma.ProgramStudiScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProgramStudiCountAggregateInputType | true
  _min?: ProgramStudiMinAggregateInputType
  _max?: ProgramStudiMaxAggregateInputType
}

export type ProgramStudiGroupByOutputType = {
  id: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt: Date
  updatedAt: Date
  _count: ProgramStudiCountAggregateOutputType | null
  _min: ProgramStudiMinAggregateOutputType | null
  _max: ProgramStudiMaxAggregateOutputType | null
}

type GetProgramStudiGroupByPayload<T extends ProgramStudiGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProgramStudiGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProgramStudiGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProgramStudiGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProgramStudiGroupByOutputType[P]>
      }
    >
  >



export type ProgramStudiWhereInput = {
  AND?: Prisma.ProgramStudiWhereInput | Prisma.ProgramStudiWhereInput[]
  OR?: Prisma.ProgramStudiWhereInput[]
  NOT?: Prisma.ProgramStudiWhereInput | Prisma.ProgramStudiWhereInput[]
  id?: Prisma.StringFilter<"ProgramStudi"> | string
  fakultas?: Prisma.EnumFakultasFilter<"ProgramStudi"> | $Enums.Fakultas
  name?: Prisma.StringFilter<"ProgramStudi"> | string
  createdAt?: Prisma.DateTimeFilter<"ProgramStudi"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProgramStudi"> | Date | string
  profiles?: Prisma.ProfileListRelationFilter
}

export type ProgramStudiOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fakultas?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profiles?: Prisma.ProfileOrderByRelationAggregateInput
}

export type ProgramStudiWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fakultas_name?: Prisma.ProgramStudiFakultasNameCompoundUniqueInput
  AND?: Prisma.ProgramStudiWhereInput | Prisma.ProgramStudiWhereInput[]
  OR?: Prisma.ProgramStudiWhereInput[]
  NOT?: Prisma.ProgramStudiWhereInput | Prisma.ProgramStudiWhereInput[]
  fakultas?: Prisma.EnumFakultasFilter<"ProgramStudi"> | $Enums.Fakultas
  name?: Prisma.StringFilter<"ProgramStudi"> | string
  createdAt?: Prisma.DateTimeFilter<"ProgramStudi"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProgramStudi"> | Date | string
  profiles?: Prisma.ProfileListRelationFilter
}, "id" | "fakultas_name">

export type ProgramStudiOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fakultas?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProgramStudiCountOrderByAggregateInput
  _max?: Prisma.ProgramStudiMaxOrderByAggregateInput
  _min?: Prisma.ProgramStudiMinOrderByAggregateInput
}

export type ProgramStudiScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProgramStudiScalarWhereWithAggregatesInput | Prisma.ProgramStudiScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProgramStudiScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProgramStudiScalarWhereWithAggregatesInput | Prisma.ProgramStudiScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProgramStudi"> | string
  fakultas?: Prisma.EnumFakultasWithAggregatesFilter<"ProgramStudi"> | $Enums.Fakultas
  name?: Prisma.StringWithAggregatesFilter<"ProgramStudi"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProgramStudi"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProgramStudi"> | Date | string
}

export type ProgramStudiCreateInput = {
  id?: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileCreateNestedManyWithoutProgramStudiInput
}

export type ProgramStudiUncheckedCreateInput = {
  id?: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutProgramStudiInput
}

export type ProgramStudiUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUpdateManyWithoutProgramStudiNestedInput
}

export type ProgramStudiUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutProgramStudiNestedInput
}

export type ProgramStudiCreateManyInput = {
  id?: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProgramStudiUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgramStudiUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgramStudiNullableScalarRelationFilter = {
  is?: Prisma.ProgramStudiWhereInput | null
  isNot?: Prisma.ProgramStudiWhereInput | null
}

export type ProgramStudiFakultasNameCompoundUniqueInput = {
  fakultas: $Enums.Fakultas
  name: string
}

export type ProgramStudiCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakultas?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgramStudiMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakultas?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgramStudiMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakultas?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgramStudiCreateNestedOneWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.ProgramStudiCreateWithoutProfilesInput, Prisma.ProgramStudiUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.ProgramStudiCreateOrConnectWithoutProfilesInput
  connect?: Prisma.ProgramStudiWhereUniqueInput
}

export type ProgramStudiUpdateOneWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramStudiCreateWithoutProfilesInput, Prisma.ProgramStudiUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.ProgramStudiCreateOrConnectWithoutProfilesInput
  upsert?: Prisma.ProgramStudiUpsertWithoutProfilesInput
  disconnect?: Prisma.ProgramStudiWhereInput | boolean
  delete?: Prisma.ProgramStudiWhereInput | boolean
  connect?: Prisma.ProgramStudiWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProgramStudiUpdateToOneWithWhereWithoutProfilesInput, Prisma.ProgramStudiUpdateWithoutProfilesInput>, Prisma.ProgramStudiUncheckedUpdateWithoutProfilesInput>
}

export type EnumFakultasFieldUpdateOperationsInput = {
  set?: $Enums.Fakultas
}

export type ProgramStudiCreateWithoutProfilesInput = {
  id?: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProgramStudiUncheckedCreateWithoutProfilesInput = {
  id?: string
  fakultas: $Enums.Fakultas
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProgramStudiCreateOrConnectWithoutProfilesInput = {
  where: Prisma.ProgramStudiWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgramStudiCreateWithoutProfilesInput, Prisma.ProgramStudiUncheckedCreateWithoutProfilesInput>
}

export type ProgramStudiUpsertWithoutProfilesInput = {
  update: Prisma.XOR<Prisma.ProgramStudiUpdateWithoutProfilesInput, Prisma.ProgramStudiUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.ProgramStudiCreateWithoutProfilesInput, Prisma.ProgramStudiUncheckedCreateWithoutProfilesInput>
  where?: Prisma.ProgramStudiWhereInput
}

export type ProgramStudiUpdateToOneWithWhereWithoutProfilesInput = {
  where?: Prisma.ProgramStudiWhereInput
  data: Prisma.XOR<Prisma.ProgramStudiUpdateWithoutProfilesInput, Prisma.ProgramStudiUncheckedUpdateWithoutProfilesInput>
}

export type ProgramStudiUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgramStudiUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakultas?: Prisma.EnumFakultasFieldUpdateOperationsInput | $Enums.Fakultas
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProgramStudiCountOutputType
 */

export type ProgramStudiCountOutputType = {
  profiles: number
}

export type ProgramStudiCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | ProgramStudiCountOutputTypeCountProfilesArgs
}

/**
 * ProgramStudiCountOutputType without action
 */
export type ProgramStudiCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudiCountOutputType
   */
  select?: Prisma.ProgramStudiCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProgramStudiCountOutputType without action
 */
export type ProgramStudiCountOutputTypeCountProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
}


export type ProgramStudiSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakultas?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profiles?: boolean | Prisma.ProgramStudi$profilesArgs<ExtArgs>
  _count?: boolean | Prisma.ProgramStudiCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programStudi"]>

export type ProgramStudiSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakultas?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["programStudi"]>

export type ProgramStudiSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakultas?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["programStudi"]>

export type ProgramStudiSelectScalar = {
  id?: boolean
  fakultas?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProgramStudiOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fakultas" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["programStudi"]>
export type ProgramStudiInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.ProgramStudi$profilesArgs<ExtArgs>
  _count?: boolean | Prisma.ProgramStudiCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProgramStudiIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProgramStudiIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProgramStudiPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProgramStudi"
  objects: {
    profiles: Prisma.$ProfilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fakultas: $Enums.Fakultas
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["programStudi"]>
  composites: {}
}

export type ProgramStudiGetPayload<S extends boolean | null | undefined | ProgramStudiDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload, S>

export type ProgramStudiCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProgramStudiFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProgramStudiCountAggregateInputType | true
  }

export interface ProgramStudiDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProgramStudi'], meta: { name: 'ProgramStudi' } }
  /**
   * Find zero or one ProgramStudi that matches the filter.
   * @param {ProgramStudiFindUniqueArgs} args - Arguments to find a ProgramStudi
   * @example
   * // Get one ProgramStudi
   * const programStudi = await prisma.programStudi.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProgramStudiFindUniqueArgs>(args: Prisma.SelectSubset<T, ProgramStudiFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProgramStudi that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProgramStudiFindUniqueOrThrowArgs} args - Arguments to find a ProgramStudi
   * @example
   * // Get one ProgramStudi
   * const programStudi = await prisma.programStudi.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProgramStudiFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProgramStudiFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramStudi that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiFindFirstArgs} args - Arguments to find a ProgramStudi
   * @example
   * // Get one ProgramStudi
   * const programStudi = await prisma.programStudi.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProgramStudiFindFirstArgs>(args?: Prisma.SelectSubset<T, ProgramStudiFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramStudi that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiFindFirstOrThrowArgs} args - Arguments to find a ProgramStudi
   * @example
   * // Get one ProgramStudi
   * const programStudi = await prisma.programStudi.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProgramStudiFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProgramStudiFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProgramStudis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProgramStudis
   * const programStudis = await prisma.programStudi.findMany()
   * 
   * // Get first 10 ProgramStudis
   * const programStudis = await prisma.programStudi.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const programStudiWithIdOnly = await prisma.programStudi.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProgramStudiFindManyArgs>(args?: Prisma.SelectSubset<T, ProgramStudiFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProgramStudi.
   * @param {ProgramStudiCreateArgs} args - Arguments to create a ProgramStudi.
   * @example
   * // Create one ProgramStudi
   * const ProgramStudi = await prisma.programStudi.create({
   *   data: {
   *     // ... data to create a ProgramStudi
   *   }
   * })
   * 
   */
  create<T extends ProgramStudiCreateArgs>(args: Prisma.SelectSubset<T, ProgramStudiCreateArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProgramStudis.
   * @param {ProgramStudiCreateManyArgs} args - Arguments to create many ProgramStudis.
   * @example
   * // Create many ProgramStudis
   * const programStudi = await prisma.programStudi.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProgramStudiCreateManyArgs>(args?: Prisma.SelectSubset<T, ProgramStudiCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProgramStudis and returns the data saved in the database.
   * @param {ProgramStudiCreateManyAndReturnArgs} args - Arguments to create many ProgramStudis.
   * @example
   * // Create many ProgramStudis
   * const programStudi = await prisma.programStudi.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProgramStudis and only return the `id`
   * const programStudiWithIdOnly = await prisma.programStudi.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProgramStudiCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProgramStudiCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProgramStudi.
   * @param {ProgramStudiDeleteArgs} args - Arguments to delete one ProgramStudi.
   * @example
   * // Delete one ProgramStudi
   * const ProgramStudi = await prisma.programStudi.delete({
   *   where: {
   *     // ... filter to delete one ProgramStudi
   *   }
   * })
   * 
   */
  delete<T extends ProgramStudiDeleteArgs>(args: Prisma.SelectSubset<T, ProgramStudiDeleteArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProgramStudi.
   * @param {ProgramStudiUpdateArgs} args - Arguments to update one ProgramStudi.
   * @example
   * // Update one ProgramStudi
   * const programStudi = await prisma.programStudi.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProgramStudiUpdateArgs>(args: Prisma.SelectSubset<T, ProgramStudiUpdateArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProgramStudis.
   * @param {ProgramStudiDeleteManyArgs} args - Arguments to filter ProgramStudis to delete.
   * @example
   * // Delete a few ProgramStudis
   * const { count } = await prisma.programStudi.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProgramStudiDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProgramStudiDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProgramStudis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProgramStudis
   * const programStudi = await prisma.programStudi.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProgramStudiUpdateManyArgs>(args: Prisma.SelectSubset<T, ProgramStudiUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProgramStudis and returns the data updated in the database.
   * @param {ProgramStudiUpdateManyAndReturnArgs} args - Arguments to update many ProgramStudis.
   * @example
   * // Update many ProgramStudis
   * const programStudi = await prisma.programStudi.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProgramStudis and only return the `id`
   * const programStudiWithIdOnly = await prisma.programStudi.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProgramStudiUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProgramStudiUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProgramStudi.
   * @param {ProgramStudiUpsertArgs} args - Arguments to update or create a ProgramStudi.
   * @example
   * // Update or create a ProgramStudi
   * const programStudi = await prisma.programStudi.upsert({
   *   create: {
   *     // ... data to create a ProgramStudi
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProgramStudi we want to update
   *   }
   * })
   */
  upsert<T extends ProgramStudiUpsertArgs>(args: Prisma.SelectSubset<T, ProgramStudiUpsertArgs<ExtArgs>>): Prisma.Prisma__ProgramStudiClient<runtime.Types.Result.GetResult<Prisma.$ProgramStudiPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProgramStudis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiCountArgs} args - Arguments to filter ProgramStudis to count.
   * @example
   * // Count the number of ProgramStudis
   * const count = await prisma.programStudi.count({
   *   where: {
   *     // ... the filter for the ProgramStudis we want to count
   *   }
   * })
  **/
  count<T extends ProgramStudiCountArgs>(
    args?: Prisma.Subset<T, ProgramStudiCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProgramStudiCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProgramStudi.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProgramStudiAggregateArgs>(args: Prisma.Subset<T, ProgramStudiAggregateArgs>): Prisma.PrismaPromise<GetProgramStudiAggregateType<T>>

  /**
   * Group by ProgramStudi.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramStudiGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProgramStudiGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProgramStudiGroupByArgs['orderBy'] }
      : { orderBy?: ProgramStudiGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProgramStudiGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProgramStudiGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProgramStudi model
 */
readonly fields: ProgramStudiFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProgramStudi.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProgramStudiClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles<T extends Prisma.ProgramStudi$profilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgramStudi$profilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProgramStudi model
 */
export interface ProgramStudiFieldRefs {
  readonly id: Prisma.FieldRef<"ProgramStudi", 'String'>
  readonly fakultas: Prisma.FieldRef<"ProgramStudi", 'Fakultas'>
  readonly name: Prisma.FieldRef<"ProgramStudi", 'String'>
  readonly createdAt: Prisma.FieldRef<"ProgramStudi", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ProgramStudi", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProgramStudi findUnique
 */
export type ProgramStudiFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter, which ProgramStudi to fetch.
   */
  where: Prisma.ProgramStudiWhereUniqueInput
}

/**
 * ProgramStudi findUniqueOrThrow
 */
export type ProgramStudiFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter, which ProgramStudi to fetch.
   */
  where: Prisma.ProgramStudiWhereUniqueInput
}

/**
 * ProgramStudi findFirst
 */
export type ProgramStudiFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter, which ProgramStudi to fetch.
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramStudis to fetch.
   */
  orderBy?: Prisma.ProgramStudiOrderByWithRelationInput | Prisma.ProgramStudiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramStudis.
   */
  cursor?: Prisma.ProgramStudiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramStudis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramStudis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramStudis.
   */
  distinct?: Prisma.ProgramStudiScalarFieldEnum | Prisma.ProgramStudiScalarFieldEnum[]
}

/**
 * ProgramStudi findFirstOrThrow
 */
export type ProgramStudiFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter, which ProgramStudi to fetch.
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramStudis to fetch.
   */
  orderBy?: Prisma.ProgramStudiOrderByWithRelationInput | Prisma.ProgramStudiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramStudis.
   */
  cursor?: Prisma.ProgramStudiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramStudis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramStudis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramStudis.
   */
  distinct?: Prisma.ProgramStudiScalarFieldEnum | Prisma.ProgramStudiScalarFieldEnum[]
}

/**
 * ProgramStudi findMany
 */
export type ProgramStudiFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter, which ProgramStudis to fetch.
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramStudis to fetch.
   */
  orderBy?: Prisma.ProgramStudiOrderByWithRelationInput | Prisma.ProgramStudiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProgramStudis.
   */
  cursor?: Prisma.ProgramStudiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramStudis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramStudis.
   */
  skip?: number
  distinct?: Prisma.ProgramStudiScalarFieldEnum | Prisma.ProgramStudiScalarFieldEnum[]
}

/**
 * ProgramStudi create
 */
export type ProgramStudiCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * The data needed to create a ProgramStudi.
   */
  data: Prisma.XOR<Prisma.ProgramStudiCreateInput, Prisma.ProgramStudiUncheckedCreateInput>
}

/**
 * ProgramStudi createMany
 */
export type ProgramStudiCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProgramStudis.
   */
  data: Prisma.ProgramStudiCreateManyInput | Prisma.ProgramStudiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProgramStudi createManyAndReturn
 */
export type ProgramStudiCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * The data used to create many ProgramStudis.
   */
  data: Prisma.ProgramStudiCreateManyInput | Prisma.ProgramStudiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProgramStudi update
 */
export type ProgramStudiUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * The data needed to update a ProgramStudi.
   */
  data: Prisma.XOR<Prisma.ProgramStudiUpdateInput, Prisma.ProgramStudiUncheckedUpdateInput>
  /**
   * Choose, which ProgramStudi to update.
   */
  where: Prisma.ProgramStudiWhereUniqueInput
}

/**
 * ProgramStudi updateMany
 */
export type ProgramStudiUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProgramStudis.
   */
  data: Prisma.XOR<Prisma.ProgramStudiUpdateManyMutationInput, Prisma.ProgramStudiUncheckedUpdateManyInput>
  /**
   * Filter which ProgramStudis to update
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * Limit how many ProgramStudis to update.
   */
  limit?: number
}

/**
 * ProgramStudi updateManyAndReturn
 */
export type ProgramStudiUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * The data used to update ProgramStudis.
   */
  data: Prisma.XOR<Prisma.ProgramStudiUpdateManyMutationInput, Prisma.ProgramStudiUncheckedUpdateManyInput>
  /**
   * Filter which ProgramStudis to update
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * Limit how many ProgramStudis to update.
   */
  limit?: number
}

/**
 * ProgramStudi upsert
 */
export type ProgramStudiUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * The filter to search for the ProgramStudi to update in case it exists.
   */
  where: Prisma.ProgramStudiWhereUniqueInput
  /**
   * In case the ProgramStudi found by the `where` argument doesn't exist, create a new ProgramStudi with this data.
   */
  create: Prisma.XOR<Prisma.ProgramStudiCreateInput, Prisma.ProgramStudiUncheckedCreateInput>
  /**
   * In case the ProgramStudi was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProgramStudiUpdateInput, Prisma.ProgramStudiUncheckedUpdateInput>
}

/**
 * ProgramStudi delete
 */
export type ProgramStudiDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
  /**
   * Filter which ProgramStudi to delete.
   */
  where: Prisma.ProgramStudiWhereUniqueInput
}

/**
 * ProgramStudi deleteMany
 */
export type ProgramStudiDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramStudis to delete
   */
  where?: Prisma.ProgramStudiWhereInput
  /**
   * Limit how many ProgramStudis to delete.
   */
  limit?: number
}

/**
 * ProgramStudi.profiles
 */
export type ProgramStudi$profilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  cursor?: Prisma.ProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * ProgramStudi without action
 */
export type ProgramStudiDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramStudi
   */
  select?: Prisma.ProgramStudiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramStudi
   */
  omit?: Prisma.ProgramStudiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramStudiInclude<ExtArgs> | null
}
