
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubDivision` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SubDivision
 * 
 */
export type SubDivisionModel = runtime.Types.Result.DefaultSelection<Prisma.$SubDivisionPayload>

export type AggregateSubDivision = {
  _count: SubDivisionCountAggregateOutputType | null
  _min: SubDivisionMinAggregateOutputType | null
  _max: SubDivisionMaxAggregateOutputType | null
}

export type SubDivisionMinAggregateOutputType = {
  id: string | null
  divisionId: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubDivisionMaxAggregateOutputType = {
  id: string | null
  divisionId: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubDivisionCountAggregateOutputType = {
  id: number
  divisionId: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SubDivisionMinAggregateInputType = {
  id?: true
  divisionId?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type SubDivisionMaxAggregateInputType = {
  id?: true
  divisionId?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type SubDivisionCountAggregateInputType = {
  id?: true
  divisionId?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SubDivisionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubDivision to aggregate.
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubDivisions to fetch.
   */
  orderBy?: Prisma.SubDivisionOrderByWithRelationInput | Prisma.SubDivisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubDivisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubDivisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubDivisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubDivisions
  **/
  _count?: true | SubDivisionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubDivisionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubDivisionMaxAggregateInputType
}

export type GetSubDivisionAggregateType<T extends SubDivisionAggregateArgs> = {
      [P in keyof T & keyof AggregateSubDivision]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubDivision[P]>
    : Prisma.GetScalarType<T[P], AggregateSubDivision[P]>
}




export type SubDivisionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubDivisionWhereInput
  orderBy?: Prisma.SubDivisionOrderByWithAggregationInput | Prisma.SubDivisionOrderByWithAggregationInput[]
  by: Prisma.SubDivisionScalarFieldEnum[] | Prisma.SubDivisionScalarFieldEnum
  having?: Prisma.SubDivisionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubDivisionCountAggregateInputType | true
  _min?: SubDivisionMinAggregateInputType
  _max?: SubDivisionMaxAggregateInputType
}

export type SubDivisionGroupByOutputType = {
  id: string
  divisionId: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: SubDivisionCountAggregateOutputType | null
  _min: SubDivisionMinAggregateOutputType | null
  _max: SubDivisionMaxAggregateOutputType | null
}

type GetSubDivisionGroupByPayload<T extends SubDivisionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubDivisionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubDivisionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubDivisionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubDivisionGroupByOutputType[P]>
      }
    >
  >



export type SubDivisionWhereInput = {
  AND?: Prisma.SubDivisionWhereInput | Prisma.SubDivisionWhereInput[]
  OR?: Prisma.SubDivisionWhereInput[]
  NOT?: Prisma.SubDivisionWhereInput | Prisma.SubDivisionWhereInput[]
  id?: Prisma.StringFilter<"SubDivision"> | string
  divisionId?: Prisma.StringFilter<"SubDivision"> | string
  name?: Prisma.StringFilter<"SubDivision"> | string
  createdAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
  division?: Prisma.XOR<Prisma.DivisionScalarRelationFilter, Prisma.DivisionWhereInput>
  profiles?: Prisma.ProfileListRelationFilter
  exams?: Prisma.ExamListRelationFilter
  learningModules?: Prisma.LearningModuleListRelationFilter
  assignments?: Prisma.AssignmentListRelationFilter
}

export type SubDivisionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  divisionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  division?: Prisma.DivisionOrderByWithRelationInput
  profiles?: Prisma.ProfileOrderByRelationAggregateInput
  exams?: Prisma.ExamOrderByRelationAggregateInput
  learningModules?: Prisma.LearningModuleOrderByRelationAggregateInput
  assignments?: Prisma.AssignmentOrderByRelationAggregateInput
}

export type SubDivisionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  divisionId_name?: Prisma.SubDivisionDivisionIdNameCompoundUniqueInput
  AND?: Prisma.SubDivisionWhereInput | Prisma.SubDivisionWhereInput[]
  OR?: Prisma.SubDivisionWhereInput[]
  NOT?: Prisma.SubDivisionWhereInput | Prisma.SubDivisionWhereInput[]
  divisionId?: Prisma.StringFilter<"SubDivision"> | string
  name?: Prisma.StringFilter<"SubDivision"> | string
  createdAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
  division?: Prisma.XOR<Prisma.DivisionScalarRelationFilter, Prisma.DivisionWhereInput>
  profiles?: Prisma.ProfileListRelationFilter
  exams?: Prisma.ExamListRelationFilter
  learningModules?: Prisma.LearningModuleListRelationFilter
  assignments?: Prisma.AssignmentListRelationFilter
}, "id" | "divisionId_name">

export type SubDivisionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  divisionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SubDivisionCountOrderByAggregateInput
  _max?: Prisma.SubDivisionMaxOrderByAggregateInput
  _min?: Prisma.SubDivisionMinOrderByAggregateInput
}

export type SubDivisionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubDivisionScalarWhereWithAggregatesInput | Prisma.SubDivisionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubDivisionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubDivisionScalarWhereWithAggregatesInput | Prisma.SubDivisionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SubDivision"> | string
  divisionId?: Prisma.StringWithAggregatesFilter<"SubDivision"> | string
  name?: Prisma.StringWithAggregatesFilter<"SubDivision"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SubDivision"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SubDivision"> | Date | string
}

export type SubDivisionCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  division: Prisma.DivisionCreateNestedOneWithoutSubDivisionsInput
  profiles?: Prisma.ProfileCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamUncheckedCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  division?: Prisma.DivisionUpdateOneRequiredWithoutSubDivisionsNestedInput
  profiles?: Prisma.ProfileUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUncheckedUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionCreateManyInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubDivisionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubDivisionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubDivisionListRelationFilter = {
  every?: Prisma.SubDivisionWhereInput
  some?: Prisma.SubDivisionWhereInput
  none?: Prisma.SubDivisionWhereInput
}

export type SubDivisionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubDivisionDivisionIdNameCompoundUniqueInput = {
  divisionId: string
  name: string
}

export type SubDivisionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  divisionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubDivisionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  divisionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubDivisionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  divisionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubDivisionNullableScalarRelationFilter = {
  is?: Prisma.SubDivisionWhereInput | null
  isNot?: Prisma.SubDivisionWhereInput | null
}

export type SubDivisionScalarRelationFilter = {
  is?: Prisma.SubDivisionWhereInput
  isNot?: Prisma.SubDivisionWhereInput
}

export type SubDivisionCreateNestedManyWithoutDivisionInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput> | Prisma.SubDivisionCreateWithoutDivisionInput[] | Prisma.SubDivisionUncheckedCreateWithoutDivisionInput[]
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutDivisionInput | Prisma.SubDivisionCreateOrConnectWithoutDivisionInput[]
  createMany?: Prisma.SubDivisionCreateManyDivisionInputEnvelope
  connect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
}

export type SubDivisionUncheckedCreateNestedManyWithoutDivisionInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput> | Prisma.SubDivisionCreateWithoutDivisionInput[] | Prisma.SubDivisionUncheckedCreateWithoutDivisionInput[]
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutDivisionInput | Prisma.SubDivisionCreateOrConnectWithoutDivisionInput[]
  createMany?: Prisma.SubDivisionCreateManyDivisionInputEnvelope
  connect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
}

export type SubDivisionUpdateManyWithoutDivisionNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput> | Prisma.SubDivisionCreateWithoutDivisionInput[] | Prisma.SubDivisionUncheckedCreateWithoutDivisionInput[]
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutDivisionInput | Prisma.SubDivisionCreateOrConnectWithoutDivisionInput[]
  upsert?: Prisma.SubDivisionUpsertWithWhereUniqueWithoutDivisionInput | Prisma.SubDivisionUpsertWithWhereUniqueWithoutDivisionInput[]
  createMany?: Prisma.SubDivisionCreateManyDivisionInputEnvelope
  set?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  disconnect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  delete?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  connect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  update?: Prisma.SubDivisionUpdateWithWhereUniqueWithoutDivisionInput | Prisma.SubDivisionUpdateWithWhereUniqueWithoutDivisionInput[]
  updateMany?: Prisma.SubDivisionUpdateManyWithWhereWithoutDivisionInput | Prisma.SubDivisionUpdateManyWithWhereWithoutDivisionInput[]
  deleteMany?: Prisma.SubDivisionScalarWhereInput | Prisma.SubDivisionScalarWhereInput[]
}

export type SubDivisionUncheckedUpdateManyWithoutDivisionNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput> | Prisma.SubDivisionCreateWithoutDivisionInput[] | Prisma.SubDivisionUncheckedCreateWithoutDivisionInput[]
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutDivisionInput | Prisma.SubDivisionCreateOrConnectWithoutDivisionInput[]
  upsert?: Prisma.SubDivisionUpsertWithWhereUniqueWithoutDivisionInput | Prisma.SubDivisionUpsertWithWhereUniqueWithoutDivisionInput[]
  createMany?: Prisma.SubDivisionCreateManyDivisionInputEnvelope
  set?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  disconnect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  delete?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  connect?: Prisma.SubDivisionWhereUniqueInput | Prisma.SubDivisionWhereUniqueInput[]
  update?: Prisma.SubDivisionUpdateWithWhereUniqueWithoutDivisionInput | Prisma.SubDivisionUpdateWithWhereUniqueWithoutDivisionInput[]
  updateMany?: Prisma.SubDivisionUpdateManyWithWhereWithoutDivisionInput | Prisma.SubDivisionUpdateManyWithWhereWithoutDivisionInput[]
  deleteMany?: Prisma.SubDivisionScalarWhereInput | Prisma.SubDivisionScalarWhereInput[]
}

export type SubDivisionCreateNestedOneWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutProfilesInput, Prisma.SubDivisionUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutProfilesInput
  connect?: Prisma.SubDivisionWhereUniqueInput
}

export type SubDivisionUpdateOneWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutProfilesInput, Prisma.SubDivisionUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutProfilesInput
  upsert?: Prisma.SubDivisionUpsertWithoutProfilesInput
  disconnect?: Prisma.SubDivisionWhereInput | boolean
  delete?: Prisma.SubDivisionWhereInput | boolean
  connect?: Prisma.SubDivisionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubDivisionUpdateToOneWithWhereWithoutProfilesInput, Prisma.SubDivisionUpdateWithoutProfilesInput>, Prisma.SubDivisionUncheckedUpdateWithoutProfilesInput>
}

export type SubDivisionCreateNestedOneWithoutExamsInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutExamsInput, Prisma.SubDivisionUncheckedCreateWithoutExamsInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutExamsInput
  connect?: Prisma.SubDivisionWhereUniqueInput
}

export type SubDivisionUpdateOneRequiredWithoutExamsNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutExamsInput, Prisma.SubDivisionUncheckedCreateWithoutExamsInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutExamsInput
  upsert?: Prisma.SubDivisionUpsertWithoutExamsInput
  connect?: Prisma.SubDivisionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubDivisionUpdateToOneWithWhereWithoutExamsInput, Prisma.SubDivisionUpdateWithoutExamsInput>, Prisma.SubDivisionUncheckedUpdateWithoutExamsInput>
}

export type SubDivisionCreateNestedOneWithoutLearningModulesInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedCreateWithoutLearningModulesInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutLearningModulesInput
  connect?: Prisma.SubDivisionWhereUniqueInput
}

export type SubDivisionUpdateOneRequiredWithoutLearningModulesNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedCreateWithoutLearningModulesInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutLearningModulesInput
  upsert?: Prisma.SubDivisionUpsertWithoutLearningModulesInput
  connect?: Prisma.SubDivisionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubDivisionUpdateToOneWithWhereWithoutLearningModulesInput, Prisma.SubDivisionUpdateWithoutLearningModulesInput>, Prisma.SubDivisionUncheckedUpdateWithoutLearningModulesInput>
}

export type SubDivisionCreateNestedOneWithoutAssignmentsInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedCreateWithoutAssignmentsInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutAssignmentsInput
  connect?: Prisma.SubDivisionWhereUniqueInput
}

export type SubDivisionUpdateOneRequiredWithoutAssignmentsNestedInput = {
  create?: Prisma.XOR<Prisma.SubDivisionCreateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedCreateWithoutAssignmentsInput>
  connectOrCreate?: Prisma.SubDivisionCreateOrConnectWithoutAssignmentsInput
  upsert?: Prisma.SubDivisionUpsertWithoutAssignmentsInput
  connect?: Prisma.SubDivisionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubDivisionUpdateToOneWithWhereWithoutAssignmentsInput, Prisma.SubDivisionUpdateWithoutAssignmentsInput>, Prisma.SubDivisionUncheckedUpdateWithoutAssignmentsInput>
}

export type SubDivisionCreateWithoutDivisionInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateWithoutDivisionInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamUncheckedCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionCreateOrConnectWithoutDivisionInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput>
}

export type SubDivisionCreateManyDivisionInputEnvelope = {
  data: Prisma.SubDivisionCreateManyDivisionInput | Prisma.SubDivisionCreateManyDivisionInput[]
  skipDuplicates?: boolean
}

export type SubDivisionUpsertWithWhereUniqueWithoutDivisionInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  update: Prisma.XOR<Prisma.SubDivisionUpdateWithoutDivisionInput, Prisma.SubDivisionUncheckedUpdateWithoutDivisionInput>
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutDivisionInput, Prisma.SubDivisionUncheckedCreateWithoutDivisionInput>
}

export type SubDivisionUpdateWithWhereUniqueWithoutDivisionInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateWithoutDivisionInput, Prisma.SubDivisionUncheckedUpdateWithoutDivisionInput>
}

export type SubDivisionUpdateManyWithWhereWithoutDivisionInput = {
  where: Prisma.SubDivisionScalarWhereInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateManyMutationInput, Prisma.SubDivisionUncheckedUpdateManyWithoutDivisionInput>
}

export type SubDivisionScalarWhereInput = {
  AND?: Prisma.SubDivisionScalarWhereInput | Prisma.SubDivisionScalarWhereInput[]
  OR?: Prisma.SubDivisionScalarWhereInput[]
  NOT?: Prisma.SubDivisionScalarWhereInput | Prisma.SubDivisionScalarWhereInput[]
  id?: Prisma.StringFilter<"SubDivision"> | string
  divisionId?: Prisma.StringFilter<"SubDivision"> | string
  name?: Prisma.StringFilter<"SubDivision"> | string
  createdAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubDivision"> | Date | string
}

export type SubDivisionCreateWithoutProfilesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  division: Prisma.DivisionCreateNestedOneWithoutSubDivisionsInput
  exams?: Prisma.ExamCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateWithoutProfilesInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  exams?: Prisma.ExamUncheckedCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionCreateOrConnectWithoutProfilesInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutProfilesInput, Prisma.SubDivisionUncheckedCreateWithoutProfilesInput>
}

export type SubDivisionUpsertWithoutProfilesInput = {
  update: Prisma.XOR<Prisma.SubDivisionUpdateWithoutProfilesInput, Prisma.SubDivisionUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutProfilesInput, Prisma.SubDivisionUncheckedCreateWithoutProfilesInput>
  where?: Prisma.SubDivisionWhereInput
}

export type SubDivisionUpdateToOneWithWhereWithoutProfilesInput = {
  where?: Prisma.SubDivisionWhereInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateWithoutProfilesInput, Prisma.SubDivisionUncheckedUpdateWithoutProfilesInput>
}

export type SubDivisionUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  division?: Prisma.DivisionUpdateOneRequiredWithoutSubDivisionsNestedInput
  exams?: Prisma.ExamUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exams?: Prisma.ExamUncheckedUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionCreateWithoutExamsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  division: Prisma.DivisionCreateNestedOneWithoutSubDivisionsInput
  profiles?: Prisma.ProfileCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateWithoutExamsInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionCreateOrConnectWithoutExamsInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutExamsInput, Prisma.SubDivisionUncheckedCreateWithoutExamsInput>
}

export type SubDivisionUpsertWithoutExamsInput = {
  update: Prisma.XOR<Prisma.SubDivisionUpdateWithoutExamsInput, Prisma.SubDivisionUncheckedUpdateWithoutExamsInput>
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutExamsInput, Prisma.SubDivisionUncheckedCreateWithoutExamsInput>
  where?: Prisma.SubDivisionWhereInput
}

export type SubDivisionUpdateToOneWithWhereWithoutExamsInput = {
  where?: Prisma.SubDivisionWhereInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateWithoutExamsInput, Prisma.SubDivisionUncheckedUpdateWithoutExamsInput>
}

export type SubDivisionUpdateWithoutExamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  division?: Prisma.DivisionUpdateOneRequiredWithoutSubDivisionsNestedInput
  profiles?: Prisma.ProfileUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateWithoutExamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionCreateWithoutLearningModulesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  division: Prisma.DivisionCreateNestedOneWithoutSubDivisionsInput
  profiles?: Prisma.ProfileCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateWithoutLearningModulesInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamUncheckedCreateNestedManyWithoutSubDivisionInput
  assignments?: Prisma.AssignmentUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionCreateOrConnectWithoutLearningModulesInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedCreateWithoutLearningModulesInput>
}

export type SubDivisionUpsertWithoutLearningModulesInput = {
  update: Prisma.XOR<Prisma.SubDivisionUpdateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedUpdateWithoutLearningModulesInput>
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedCreateWithoutLearningModulesInput>
  where?: Prisma.SubDivisionWhereInput
}

export type SubDivisionUpdateToOneWithWhereWithoutLearningModulesInput = {
  where?: Prisma.SubDivisionWhereInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateWithoutLearningModulesInput, Prisma.SubDivisionUncheckedUpdateWithoutLearningModulesInput>
}

export type SubDivisionUpdateWithoutLearningModulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  division?: Prisma.DivisionUpdateOneRequiredWithoutSubDivisionsNestedInput
  profiles?: Prisma.ProfileUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateWithoutLearningModulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUncheckedUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionCreateWithoutAssignmentsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  division: Prisma.DivisionCreateNestedOneWithoutSubDivisionsInput
  profiles?: Prisma.ProfileCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionUncheckedCreateWithoutAssignmentsInput = {
  id?: string
  divisionId: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profiles?: Prisma.ProfileUncheckedCreateNestedManyWithoutSubDivisionInput
  exams?: Prisma.ExamUncheckedCreateNestedManyWithoutSubDivisionInput
  learningModules?: Prisma.LearningModuleUncheckedCreateNestedManyWithoutSubDivisionInput
}

export type SubDivisionCreateOrConnectWithoutAssignmentsInput = {
  where: Prisma.SubDivisionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedCreateWithoutAssignmentsInput>
}

export type SubDivisionUpsertWithoutAssignmentsInput = {
  update: Prisma.XOR<Prisma.SubDivisionUpdateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedUpdateWithoutAssignmentsInput>
  create: Prisma.XOR<Prisma.SubDivisionCreateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedCreateWithoutAssignmentsInput>
  where?: Prisma.SubDivisionWhereInput
}

export type SubDivisionUpdateToOneWithWhereWithoutAssignmentsInput = {
  where?: Prisma.SubDivisionWhereInput
  data: Prisma.XOR<Prisma.SubDivisionUpdateWithoutAssignmentsInput, Prisma.SubDivisionUncheckedUpdateWithoutAssignmentsInput>
}

export type SubDivisionUpdateWithoutAssignmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  division?: Prisma.DivisionUpdateOneRequiredWithoutSubDivisionsNestedInput
  profiles?: Prisma.ProfileUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateWithoutAssignmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  divisionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUncheckedUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionCreateManyDivisionInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubDivisionUpdateWithoutDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateWithoutDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profiles?: Prisma.ProfileUncheckedUpdateManyWithoutSubDivisionNestedInput
  exams?: Prisma.ExamUncheckedUpdateManyWithoutSubDivisionNestedInput
  learningModules?: Prisma.LearningModuleUncheckedUpdateManyWithoutSubDivisionNestedInput
  assignments?: Prisma.AssignmentUncheckedUpdateManyWithoutSubDivisionNestedInput
}

export type SubDivisionUncheckedUpdateManyWithoutDivisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SubDivisionCountOutputType
 */

export type SubDivisionCountOutputType = {
  profiles: number
  exams: number
  learningModules: number
  assignments: number
}

export type SubDivisionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | SubDivisionCountOutputTypeCountProfilesArgs
  exams?: boolean | SubDivisionCountOutputTypeCountExamsArgs
  learningModules?: boolean | SubDivisionCountOutputTypeCountLearningModulesArgs
  assignments?: boolean | SubDivisionCountOutputTypeCountAssignmentsArgs
}

/**
 * SubDivisionCountOutputType without action
 */
export type SubDivisionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivisionCountOutputType
   */
  select?: Prisma.SubDivisionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SubDivisionCountOutputType without action
 */
export type SubDivisionCountOutputTypeCountProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
}

/**
 * SubDivisionCountOutputType without action
 */
export type SubDivisionCountOutputTypeCountExamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExamWhereInput
}

/**
 * SubDivisionCountOutputType without action
 */
export type SubDivisionCountOutputTypeCountLearningModulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LearningModuleWhereInput
}

/**
 * SubDivisionCountOutputType without action
 */
export type SubDivisionCountOutputTypeCountAssignmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssignmentWhereInput
}


export type SubDivisionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  divisionId?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.SubDivision$profilesArgs<ExtArgs>
  exams?: boolean | Prisma.SubDivision$examsArgs<ExtArgs>
  learningModules?: boolean | Prisma.SubDivision$learningModulesArgs<ExtArgs>
  assignments?: boolean | Prisma.SubDivision$assignmentsArgs<ExtArgs>
  _count?: boolean | Prisma.SubDivisionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subDivision"]>

export type SubDivisionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  divisionId?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subDivision"]>

export type SubDivisionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  divisionId?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subDivision"]>

export type SubDivisionSelectScalar = {
  id?: boolean
  divisionId?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SubDivisionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "divisionId" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["subDivision"]>
export type SubDivisionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.SubDivision$profilesArgs<ExtArgs>
  exams?: boolean | Prisma.SubDivision$examsArgs<ExtArgs>
  learningModules?: boolean | Prisma.SubDivision$learningModulesArgs<ExtArgs>
  assignments?: boolean | Prisma.SubDivision$assignmentsArgs<ExtArgs>
  _count?: boolean | Prisma.SubDivisionCountOutputTypeDefaultArgs<ExtArgs>
}
export type SubDivisionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
}
export type SubDivisionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  division?: boolean | Prisma.DivisionDefaultArgs<ExtArgs>
}

export type $SubDivisionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubDivision"
  objects: {
    division: Prisma.$DivisionPayload<ExtArgs>
    profiles: Prisma.$ProfilePayload<ExtArgs>[]
    exams: Prisma.$ExamPayload<ExtArgs>[]
    learningModules: Prisma.$LearningModulePayload<ExtArgs>[]
    assignments: Prisma.$AssignmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    divisionId: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["subDivision"]>
  composites: {}
}

export type SubDivisionGetPayload<S extends boolean | null | undefined | SubDivisionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload, S>

export type SubDivisionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubDivisionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubDivisionCountAggregateInputType | true
  }

export interface SubDivisionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubDivision'], meta: { name: 'SubDivision' } }
  /**
   * Find zero or one SubDivision that matches the filter.
   * @param {SubDivisionFindUniqueArgs} args - Arguments to find a SubDivision
   * @example
   * // Get one SubDivision
   * const subDivision = await prisma.subDivision.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubDivisionFindUniqueArgs>(args: Prisma.SelectSubset<T, SubDivisionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubDivision that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubDivisionFindUniqueOrThrowArgs} args - Arguments to find a SubDivision
   * @example
   * // Get one SubDivision
   * const subDivision = await prisma.subDivision.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubDivisionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubDivisionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubDivision that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionFindFirstArgs} args - Arguments to find a SubDivision
   * @example
   * // Get one SubDivision
   * const subDivision = await prisma.subDivision.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubDivisionFindFirstArgs>(args?: Prisma.SelectSubset<T, SubDivisionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubDivision that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionFindFirstOrThrowArgs} args - Arguments to find a SubDivision
   * @example
   * // Get one SubDivision
   * const subDivision = await prisma.subDivision.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubDivisionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubDivisionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubDivisions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubDivisions
   * const subDivisions = await prisma.subDivision.findMany()
   * 
   * // Get first 10 SubDivisions
   * const subDivisions = await prisma.subDivision.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const subDivisionWithIdOnly = await prisma.subDivision.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubDivisionFindManyArgs>(args?: Prisma.SelectSubset<T, SubDivisionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubDivision.
   * @param {SubDivisionCreateArgs} args - Arguments to create a SubDivision.
   * @example
   * // Create one SubDivision
   * const SubDivision = await prisma.subDivision.create({
   *   data: {
   *     // ... data to create a SubDivision
   *   }
   * })
   * 
   */
  create<T extends SubDivisionCreateArgs>(args: Prisma.SelectSubset<T, SubDivisionCreateArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubDivisions.
   * @param {SubDivisionCreateManyArgs} args - Arguments to create many SubDivisions.
   * @example
   * // Create many SubDivisions
   * const subDivision = await prisma.subDivision.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubDivisionCreateManyArgs>(args?: Prisma.SelectSubset<T, SubDivisionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubDivisions and returns the data saved in the database.
   * @param {SubDivisionCreateManyAndReturnArgs} args - Arguments to create many SubDivisions.
   * @example
   * // Create many SubDivisions
   * const subDivision = await prisma.subDivision.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubDivisions and only return the `id`
   * const subDivisionWithIdOnly = await prisma.subDivision.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubDivisionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubDivisionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubDivision.
   * @param {SubDivisionDeleteArgs} args - Arguments to delete one SubDivision.
   * @example
   * // Delete one SubDivision
   * const SubDivision = await prisma.subDivision.delete({
   *   where: {
   *     // ... filter to delete one SubDivision
   *   }
   * })
   * 
   */
  delete<T extends SubDivisionDeleteArgs>(args: Prisma.SelectSubset<T, SubDivisionDeleteArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubDivision.
   * @param {SubDivisionUpdateArgs} args - Arguments to update one SubDivision.
   * @example
   * // Update one SubDivision
   * const subDivision = await prisma.subDivision.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubDivisionUpdateArgs>(args: Prisma.SelectSubset<T, SubDivisionUpdateArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubDivisions.
   * @param {SubDivisionDeleteManyArgs} args - Arguments to filter SubDivisions to delete.
   * @example
   * // Delete a few SubDivisions
   * const { count } = await prisma.subDivision.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubDivisionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubDivisionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubDivisions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubDivisions
   * const subDivision = await prisma.subDivision.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubDivisionUpdateManyArgs>(args: Prisma.SelectSubset<T, SubDivisionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubDivisions and returns the data updated in the database.
   * @param {SubDivisionUpdateManyAndReturnArgs} args - Arguments to update many SubDivisions.
   * @example
   * // Update many SubDivisions
   * const subDivision = await prisma.subDivision.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubDivisions and only return the `id`
   * const subDivisionWithIdOnly = await prisma.subDivision.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubDivisionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubDivisionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubDivision.
   * @param {SubDivisionUpsertArgs} args - Arguments to update or create a SubDivision.
   * @example
   * // Update or create a SubDivision
   * const subDivision = await prisma.subDivision.upsert({
   *   create: {
   *     // ... data to create a SubDivision
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubDivision we want to update
   *   }
   * })
   */
  upsert<T extends SubDivisionUpsertArgs>(args: Prisma.SelectSubset<T, SubDivisionUpsertArgs<ExtArgs>>): Prisma.Prisma__SubDivisionClient<runtime.Types.Result.GetResult<Prisma.$SubDivisionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubDivisions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionCountArgs} args - Arguments to filter SubDivisions to count.
   * @example
   * // Count the number of SubDivisions
   * const count = await prisma.subDivision.count({
   *   where: {
   *     // ... the filter for the SubDivisions we want to count
   *   }
   * })
  **/
  count<T extends SubDivisionCountArgs>(
    args?: Prisma.Subset<T, SubDivisionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubDivisionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubDivision.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubDivisionAggregateArgs>(args: Prisma.Subset<T, SubDivisionAggregateArgs>): Prisma.PrismaPromise<GetSubDivisionAggregateType<T>>

  /**
   * Group by SubDivision.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubDivisionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubDivisionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubDivisionGroupByArgs['orderBy'] }
      : { orderBy?: SubDivisionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubDivisionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubDivisionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubDivision model
 */
readonly fields: SubDivisionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubDivision.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubDivisionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  division<T extends Prisma.DivisionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DivisionDefaultArgs<ExtArgs>>): Prisma.Prisma__DivisionClient<runtime.Types.Result.GetResult<Prisma.$DivisionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profiles<T extends Prisma.SubDivision$profilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubDivision$profilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  exams<T extends Prisma.SubDivision$examsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubDivision$examsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  learningModules<T extends Prisma.SubDivision$learningModulesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubDivision$learningModulesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningModulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assignments<T extends Prisma.SubDivision$assignmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubDivision$assignmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssignmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubDivision model
 */
export interface SubDivisionFieldRefs {
  readonly id: Prisma.FieldRef<"SubDivision", 'String'>
  readonly divisionId: Prisma.FieldRef<"SubDivision", 'String'>
  readonly name: Prisma.FieldRef<"SubDivision", 'String'>
  readonly createdAt: Prisma.FieldRef<"SubDivision", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SubDivision", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SubDivision findUnique
 */
export type SubDivisionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter, which SubDivision to fetch.
   */
  where: Prisma.SubDivisionWhereUniqueInput
}

/**
 * SubDivision findUniqueOrThrow
 */
export type SubDivisionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter, which SubDivision to fetch.
   */
  where: Prisma.SubDivisionWhereUniqueInput
}

/**
 * SubDivision findFirst
 */
export type SubDivisionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter, which SubDivision to fetch.
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubDivisions to fetch.
   */
  orderBy?: Prisma.SubDivisionOrderByWithRelationInput | Prisma.SubDivisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubDivisions.
   */
  cursor?: Prisma.SubDivisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubDivisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubDivisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubDivisions.
   */
  distinct?: Prisma.SubDivisionScalarFieldEnum | Prisma.SubDivisionScalarFieldEnum[]
}

/**
 * SubDivision findFirstOrThrow
 */
export type SubDivisionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter, which SubDivision to fetch.
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubDivisions to fetch.
   */
  orderBy?: Prisma.SubDivisionOrderByWithRelationInput | Prisma.SubDivisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubDivisions.
   */
  cursor?: Prisma.SubDivisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubDivisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubDivisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubDivisions.
   */
  distinct?: Prisma.SubDivisionScalarFieldEnum | Prisma.SubDivisionScalarFieldEnum[]
}

/**
 * SubDivision findMany
 */
export type SubDivisionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter, which SubDivisions to fetch.
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubDivisions to fetch.
   */
  orderBy?: Prisma.SubDivisionOrderByWithRelationInput | Prisma.SubDivisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubDivisions.
   */
  cursor?: Prisma.SubDivisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubDivisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubDivisions.
   */
  skip?: number
  distinct?: Prisma.SubDivisionScalarFieldEnum | Prisma.SubDivisionScalarFieldEnum[]
}

/**
 * SubDivision create
 */
export type SubDivisionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * The data needed to create a SubDivision.
   */
  data: Prisma.XOR<Prisma.SubDivisionCreateInput, Prisma.SubDivisionUncheckedCreateInput>
}

/**
 * SubDivision createMany
 */
export type SubDivisionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubDivisions.
   */
  data: Prisma.SubDivisionCreateManyInput | Prisma.SubDivisionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubDivision createManyAndReturn
 */
export type SubDivisionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * The data used to create many SubDivisions.
   */
  data: Prisma.SubDivisionCreateManyInput | Prisma.SubDivisionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubDivision update
 */
export type SubDivisionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * The data needed to update a SubDivision.
   */
  data: Prisma.XOR<Prisma.SubDivisionUpdateInput, Prisma.SubDivisionUncheckedUpdateInput>
  /**
   * Choose, which SubDivision to update.
   */
  where: Prisma.SubDivisionWhereUniqueInput
}

/**
 * SubDivision updateMany
 */
export type SubDivisionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubDivisions.
   */
  data: Prisma.XOR<Prisma.SubDivisionUpdateManyMutationInput, Prisma.SubDivisionUncheckedUpdateManyInput>
  /**
   * Filter which SubDivisions to update
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * Limit how many SubDivisions to update.
   */
  limit?: number
}

/**
 * SubDivision updateManyAndReturn
 */
export type SubDivisionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * The data used to update SubDivisions.
   */
  data: Prisma.XOR<Prisma.SubDivisionUpdateManyMutationInput, Prisma.SubDivisionUncheckedUpdateManyInput>
  /**
   * Filter which SubDivisions to update
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * Limit how many SubDivisions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubDivision upsert
 */
export type SubDivisionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * The filter to search for the SubDivision to update in case it exists.
   */
  where: Prisma.SubDivisionWhereUniqueInput
  /**
   * In case the SubDivision found by the `where` argument doesn't exist, create a new SubDivision with this data.
   */
  create: Prisma.XOR<Prisma.SubDivisionCreateInput, Prisma.SubDivisionUncheckedCreateInput>
  /**
   * In case the SubDivision was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubDivisionUpdateInput, Prisma.SubDivisionUncheckedUpdateInput>
}

/**
 * SubDivision delete
 */
export type SubDivisionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
  /**
   * Filter which SubDivision to delete.
   */
  where: Prisma.SubDivisionWhereUniqueInput
}

/**
 * SubDivision deleteMany
 */
export type SubDivisionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubDivisions to delete
   */
  where?: Prisma.SubDivisionWhereInput
  /**
   * Limit how many SubDivisions to delete.
   */
  limit?: number
}

/**
 * SubDivision.profiles
 */
export type SubDivision$profilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  cursor?: Prisma.ProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * SubDivision.exams
 */
export type SubDivision$examsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exam
   */
  select?: Prisma.ExamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exam
   */
  omit?: Prisma.ExamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExamInclude<ExtArgs> | null
  where?: Prisma.ExamWhereInput
  orderBy?: Prisma.ExamOrderByWithRelationInput | Prisma.ExamOrderByWithRelationInput[]
  cursor?: Prisma.ExamWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExamScalarFieldEnum | Prisma.ExamScalarFieldEnum[]
}

/**
 * SubDivision.learningModules
 */
export type SubDivision$learningModulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningModule
   */
  select?: Prisma.LearningModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningModule
   */
  omit?: Prisma.LearningModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningModuleInclude<ExtArgs> | null
  where?: Prisma.LearningModuleWhereInput
  orderBy?: Prisma.LearningModuleOrderByWithRelationInput | Prisma.LearningModuleOrderByWithRelationInput[]
  cursor?: Prisma.LearningModuleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LearningModuleScalarFieldEnum | Prisma.LearningModuleScalarFieldEnum[]
}

/**
 * SubDivision.assignments
 */
export type SubDivision$assignmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment
   */
  select?: Prisma.AssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment
   */
  omit?: Prisma.AssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignmentInclude<ExtArgs> | null
  where?: Prisma.AssignmentWhereInput
  orderBy?: Prisma.AssignmentOrderByWithRelationInput | Prisma.AssignmentOrderByWithRelationInput[]
  cursor?: Prisma.AssignmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssignmentScalarFieldEnum | Prisma.AssignmentScalarFieldEnum[]
}

/**
 * SubDivision without action
 */
export type SubDivisionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubDivision
   */
  select?: Prisma.SubDivisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubDivision
   */
  omit?: Prisma.SubDivisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubDivisionInclude<ExtArgs> | null
}
