
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubmissionVerification` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SubmissionVerification
 * 
 */
export type SubmissionVerificationModel = runtime.Types.Result.DefaultSelection<Prisma.$SubmissionVerificationPayload>

export type AggregateSubmissionVerification = {
  _count: SubmissionVerificationCountAggregateOutputType | null
  _min: SubmissionVerificationMinAggregateOutputType | null
  _max: SubmissionVerificationMaxAggregateOutputType | null
}

export type SubmissionVerificationMinAggregateOutputType = {
  id: string | null
  userId: string | null
  krsScanUrl: string | null
  formalPhotoUrl: string | null
  instagramProofUrl: string | null
  instagramMarketingProofUrl: string | null
  twibbonLink: string | null
  status: $Enums.VerificationStatus | null
  rejectionReason: string | null
  reviewedByAdminId: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubmissionVerificationMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  krsScanUrl: string | null
  formalPhotoUrl: string | null
  instagramProofUrl: string | null
  instagramMarketingProofUrl: string | null
  twibbonLink: string | null
  status: $Enums.VerificationStatus | null
  rejectionReason: string | null
  reviewedByAdminId: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubmissionVerificationCountAggregateOutputType = {
  id: number
  userId: number
  krsScanUrl: number
  formalPhotoUrl: number
  instagramProofUrl: number
  instagramMarketingProofUrl: number
  twibbonLink: number
  status: number
  rejectionReason: number
  reviewedByAdminId: number
  reviewedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SubmissionVerificationMinAggregateInputType = {
  id?: true
  userId?: true
  krsScanUrl?: true
  formalPhotoUrl?: true
  instagramProofUrl?: true
  instagramMarketingProofUrl?: true
  twibbonLink?: true
  status?: true
  rejectionReason?: true
  reviewedByAdminId?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type SubmissionVerificationMaxAggregateInputType = {
  id?: true
  userId?: true
  krsScanUrl?: true
  formalPhotoUrl?: true
  instagramProofUrl?: true
  instagramMarketingProofUrl?: true
  twibbonLink?: true
  status?: true
  rejectionReason?: true
  reviewedByAdminId?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type SubmissionVerificationCountAggregateInputType = {
  id?: true
  userId?: true
  krsScanUrl?: true
  formalPhotoUrl?: true
  instagramProofUrl?: true
  instagramMarketingProofUrl?: true
  twibbonLink?: true
  status?: true
  rejectionReason?: true
  reviewedByAdminId?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SubmissionVerificationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubmissionVerification to aggregate.
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionVerifications to fetch.
   */
  orderBy?: Prisma.SubmissionVerificationOrderByWithRelationInput | Prisma.SubmissionVerificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubmissionVerificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionVerifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionVerifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubmissionVerifications
  **/
  _count?: true | SubmissionVerificationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubmissionVerificationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubmissionVerificationMaxAggregateInputType
}

export type GetSubmissionVerificationAggregateType<T extends SubmissionVerificationAggregateArgs> = {
      [P in keyof T & keyof AggregateSubmissionVerification]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubmissionVerification[P]>
    : Prisma.GetScalarType<T[P], AggregateSubmissionVerification[P]>
}




export type SubmissionVerificationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubmissionVerificationWhereInput
  orderBy?: Prisma.SubmissionVerificationOrderByWithAggregationInput | Prisma.SubmissionVerificationOrderByWithAggregationInput[]
  by: Prisma.SubmissionVerificationScalarFieldEnum[] | Prisma.SubmissionVerificationScalarFieldEnum
  having?: Prisma.SubmissionVerificationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubmissionVerificationCountAggregateInputType | true
  _min?: SubmissionVerificationMinAggregateInputType
  _max?: SubmissionVerificationMaxAggregateInputType
}

export type SubmissionVerificationGroupByOutputType = {
  id: string
  userId: string
  krsScanUrl: string | null
  formalPhotoUrl: string | null
  instagramProofUrl: string | null
  instagramMarketingProofUrl: string | null
  twibbonLink: string | null
  status: $Enums.VerificationStatus
  rejectionReason: string | null
  reviewedByAdminId: string | null
  reviewedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: SubmissionVerificationCountAggregateOutputType | null
  _min: SubmissionVerificationMinAggregateOutputType | null
  _max: SubmissionVerificationMaxAggregateOutputType | null
}

type GetSubmissionVerificationGroupByPayload<T extends SubmissionVerificationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubmissionVerificationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubmissionVerificationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubmissionVerificationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubmissionVerificationGroupByOutputType[P]>
      }
    >
  >



export type SubmissionVerificationWhereInput = {
  AND?: Prisma.SubmissionVerificationWhereInput | Prisma.SubmissionVerificationWhereInput[]
  OR?: Prisma.SubmissionVerificationWhereInput[]
  NOT?: Prisma.SubmissionVerificationWhereInput | Prisma.SubmissionVerificationWhereInput[]
  id?: Prisma.StringFilter<"SubmissionVerification"> | string
  userId?: Prisma.StringFilter<"SubmissionVerification"> | string
  krsScanUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  formalPhotoUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramMarketingProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  twibbonLink?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  status?: Prisma.EnumVerificationStatusFilter<"SubmissionVerification"> | $Enums.VerificationStatus
  rejectionReason?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedByAdminId?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"SubmissionVerification"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reviewedByAdmin?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type SubmissionVerificationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  krsScanUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  formalPhotoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  instagramProofUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  instagramMarketingProofUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  twibbonLink?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedByAdminId?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  reviewedByAdmin?: Prisma.UserOrderByWithRelationInput
}

export type SubmissionVerificationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SubmissionVerificationWhereInput | Prisma.SubmissionVerificationWhereInput[]
  OR?: Prisma.SubmissionVerificationWhereInput[]
  NOT?: Prisma.SubmissionVerificationWhereInput | Prisma.SubmissionVerificationWhereInput[]
  userId?: Prisma.StringFilter<"SubmissionVerification"> | string
  krsScanUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  formalPhotoUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramMarketingProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  twibbonLink?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  status?: Prisma.EnumVerificationStatusFilter<"SubmissionVerification"> | $Enums.VerificationStatus
  rejectionReason?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedByAdminId?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"SubmissionVerification"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reviewedByAdmin?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type SubmissionVerificationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  krsScanUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  formalPhotoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  instagramProofUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  instagramMarketingProofUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  twibbonLink?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedByAdminId?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SubmissionVerificationCountOrderByAggregateInput
  _max?: Prisma.SubmissionVerificationMaxOrderByAggregateInput
  _min?: Prisma.SubmissionVerificationMinOrderByAggregateInput
}

export type SubmissionVerificationScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubmissionVerificationScalarWhereWithAggregatesInput | Prisma.SubmissionVerificationScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubmissionVerificationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubmissionVerificationScalarWhereWithAggregatesInput | Prisma.SubmissionVerificationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SubmissionVerification"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SubmissionVerification"> | string
  krsScanUrl?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  formalPhotoUrl?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  instagramProofUrl?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  instagramMarketingProofUrl?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  twibbonLink?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  status?: Prisma.EnumVerificationStatusWithAggregatesFilter<"SubmissionVerification"> | $Enums.VerificationStatus
  rejectionReason?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  reviewedByAdminId?: Prisma.StringNullableWithAggregatesFilter<"SubmissionVerification"> | string | null
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SubmissionVerification"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SubmissionVerification"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SubmissionVerification"> | Date | string
}

export type SubmissionVerificationCreateInput = {
  id?: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSubmissionVerificationsInput
  reviewedByAdmin?: Prisma.UserCreateNestedOneWithoutReviewedVerificationsInput
}

export type SubmissionVerificationUncheckedCreateInput = {
  id?: string
  userId: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedByAdminId?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSubmissionVerificationsNestedInput
  reviewedByAdmin?: Prisma.UserUpdateOneWithoutReviewedVerificationsNestedInput
}

export type SubmissionVerificationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationCreateManyInput = {
  id?: string
  userId: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedByAdminId?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationListRelationFilter = {
  every?: Prisma.SubmissionVerificationWhereInput
  some?: Prisma.SubmissionVerificationWhereInput
  none?: Prisma.SubmissionVerificationWhereInput
}

export type SubmissionVerificationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubmissionVerificationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  krsScanUrl?: Prisma.SortOrder
  formalPhotoUrl?: Prisma.SortOrder
  instagramProofUrl?: Prisma.SortOrder
  instagramMarketingProofUrl?: Prisma.SortOrder
  twibbonLink?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  reviewedByAdminId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionVerificationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  krsScanUrl?: Prisma.SortOrder
  formalPhotoUrl?: Prisma.SortOrder
  instagramProofUrl?: Prisma.SortOrder
  instagramMarketingProofUrl?: Prisma.SortOrder
  twibbonLink?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  reviewedByAdminId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionVerificationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  krsScanUrl?: Prisma.SortOrder
  formalPhotoUrl?: Prisma.SortOrder
  instagramProofUrl?: Prisma.SortOrder
  instagramMarketingProofUrl?: Prisma.SortOrder
  twibbonLink?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  reviewedByAdminId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionVerificationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput> | Prisma.SubmissionVerificationCreateWithoutUserInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput | Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyUserInputEnvelope
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
}

export type SubmissionVerificationCreateNestedManyWithoutReviewedByAdminInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput> | Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput | Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyReviewedByAdminInputEnvelope
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
}

export type SubmissionVerificationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput> | Prisma.SubmissionVerificationCreateWithoutUserInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput | Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyUserInputEnvelope
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
}

export type SubmissionVerificationUncheckedCreateNestedManyWithoutReviewedByAdminInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput> | Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput | Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyReviewedByAdminInputEnvelope
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
}

export type SubmissionVerificationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput> | Prisma.SubmissionVerificationCreateWithoutUserInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput | Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutUserInput | Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyUserInputEnvelope
  set?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  disconnect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  delete?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  update?: Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutUserInput | Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SubmissionVerificationUpdateManyWithWhereWithoutUserInput | Prisma.SubmissionVerificationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
}

export type SubmissionVerificationUpdateManyWithoutReviewedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput> | Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput | Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput[]
  upsert?: Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutReviewedByAdminInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyReviewedByAdminInputEnvelope
  set?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  disconnect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  delete?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  update?: Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutReviewedByAdminInput[]
  updateMany?: Prisma.SubmissionVerificationUpdateManyWithWhereWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpdateManyWithWhereWithoutReviewedByAdminInput[]
  deleteMany?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
}

export type SubmissionVerificationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput> | Prisma.SubmissionVerificationCreateWithoutUserInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput | Prisma.SubmissionVerificationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutUserInput | Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyUserInputEnvelope
  set?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  disconnect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  delete?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  update?: Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutUserInput | Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SubmissionVerificationUpdateManyWithWhereWithoutUserInput | Prisma.SubmissionVerificationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
}

export type SubmissionVerificationUncheckedUpdateManyWithoutReviewedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput> | Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput[] | Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput[]
  connectOrCreate?: Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput | Prisma.SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput[]
  upsert?: Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpsertWithWhereUniqueWithoutReviewedByAdminInput[]
  createMany?: Prisma.SubmissionVerificationCreateManyReviewedByAdminInputEnvelope
  set?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  disconnect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  delete?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  connect?: Prisma.SubmissionVerificationWhereUniqueInput | Prisma.SubmissionVerificationWhereUniqueInput[]
  update?: Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpdateWithWhereUniqueWithoutReviewedByAdminInput[]
  updateMany?: Prisma.SubmissionVerificationUpdateManyWithWhereWithoutReviewedByAdminInput | Prisma.SubmissionVerificationUpdateManyWithWhereWithoutReviewedByAdminInput[]
  deleteMany?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
}

export type EnumVerificationStatusFieldUpdateOperationsInput = {
  set?: $Enums.VerificationStatus
}

export type SubmissionVerificationCreateWithoutUserInput = {
  id?: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reviewedByAdmin?: Prisma.UserCreateNestedOneWithoutReviewedVerificationsInput
}

export type SubmissionVerificationUncheckedCreateWithoutUserInput = {
  id?: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedByAdminId?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationCreateOrConnectWithoutUserInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput>
}

export type SubmissionVerificationCreateManyUserInputEnvelope = {
  data: Prisma.SubmissionVerificationCreateManyUserInput | Prisma.SubmissionVerificationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SubmissionVerificationCreateWithoutReviewedByAdminInput = {
  id?: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSubmissionVerificationsInput
}

export type SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput = {
  id?: string
  userId: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationCreateOrConnectWithoutReviewedByAdminInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput>
}

export type SubmissionVerificationCreateManyReviewedByAdminInputEnvelope = {
  data: Prisma.SubmissionVerificationCreateManyReviewedByAdminInput | Prisma.SubmissionVerificationCreateManyReviewedByAdminInput[]
  skipDuplicates?: boolean
}

export type SubmissionVerificationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  update: Prisma.XOR<Prisma.SubmissionVerificationUpdateWithoutUserInput, Prisma.SubmissionVerificationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutUserInput, Prisma.SubmissionVerificationUncheckedCreateWithoutUserInput>
}

export type SubmissionVerificationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateWithoutUserInput, Prisma.SubmissionVerificationUncheckedUpdateWithoutUserInput>
}

export type SubmissionVerificationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SubmissionVerificationScalarWhereInput
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateManyMutationInput, Prisma.SubmissionVerificationUncheckedUpdateManyWithoutUserInput>
}

export type SubmissionVerificationScalarWhereInput = {
  AND?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
  OR?: Prisma.SubmissionVerificationScalarWhereInput[]
  NOT?: Prisma.SubmissionVerificationScalarWhereInput | Prisma.SubmissionVerificationScalarWhereInput[]
  id?: Prisma.StringFilter<"SubmissionVerification"> | string
  userId?: Prisma.StringFilter<"SubmissionVerification"> | string
  krsScanUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  formalPhotoUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  instagramMarketingProofUrl?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  twibbonLink?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  status?: Prisma.EnumVerificationStatusFilter<"SubmissionVerification"> | $Enums.VerificationStatus
  rejectionReason?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedByAdminId?: Prisma.StringNullableFilter<"SubmissionVerification"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"SubmissionVerification"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionVerification"> | Date | string
}

export type SubmissionVerificationUpsertWithWhereUniqueWithoutReviewedByAdminInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  update: Prisma.XOR<Prisma.SubmissionVerificationUpdateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedUpdateWithoutReviewedByAdminInput>
  create: Prisma.XOR<Prisma.SubmissionVerificationCreateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedCreateWithoutReviewedByAdminInput>
}

export type SubmissionVerificationUpdateWithWhereUniqueWithoutReviewedByAdminInput = {
  where: Prisma.SubmissionVerificationWhereUniqueInput
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateWithoutReviewedByAdminInput, Prisma.SubmissionVerificationUncheckedUpdateWithoutReviewedByAdminInput>
}

export type SubmissionVerificationUpdateManyWithWhereWithoutReviewedByAdminInput = {
  where: Prisma.SubmissionVerificationScalarWhereInput
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateManyMutationInput, Prisma.SubmissionVerificationUncheckedUpdateManyWithoutReviewedByAdminInput>
}

export type SubmissionVerificationCreateManyUserInput = {
  id?: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedByAdminId?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationCreateManyReviewedByAdminInput = {
  id?: string
  userId: string
  krsScanUrl?: string | null
  formalPhotoUrl?: string | null
  instagramProofUrl?: string | null
  instagramMarketingProofUrl?: string | null
  twibbonLink?: string | null
  status?: $Enums.VerificationStatus
  rejectionReason?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionVerificationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedByAdmin?: Prisma.UserUpdateOneWithoutReviewedVerificationsNestedInput
}

export type SubmissionVerificationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationUpdateWithoutReviewedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSubmissionVerificationsNestedInput
}

export type SubmissionVerificationUncheckedUpdateWithoutReviewedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionVerificationUncheckedUpdateManyWithoutReviewedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  krsScanUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  formalPhotoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instagramMarketingProofUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twibbonLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SubmissionVerificationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  krsScanUrl?: boolean
  formalPhotoUrl?: boolean
  instagramProofUrl?: boolean
  instagramMarketingProofUrl?: boolean
  twibbonLink?: boolean
  status?: boolean
  rejectionReason?: boolean
  reviewedByAdminId?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["submissionVerification"]>

export type SubmissionVerificationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  krsScanUrl?: boolean
  formalPhotoUrl?: boolean
  instagramProofUrl?: boolean
  instagramMarketingProofUrl?: boolean
  twibbonLink?: boolean
  status?: boolean
  rejectionReason?: boolean
  reviewedByAdminId?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["submissionVerification"]>

export type SubmissionVerificationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  krsScanUrl?: boolean
  formalPhotoUrl?: boolean
  instagramProofUrl?: boolean
  instagramMarketingProofUrl?: boolean
  twibbonLink?: boolean
  status?: boolean
  rejectionReason?: boolean
  reviewedByAdminId?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["submissionVerification"]>

export type SubmissionVerificationSelectScalar = {
  id?: boolean
  userId?: boolean
  krsScanUrl?: boolean
  formalPhotoUrl?: boolean
  instagramProofUrl?: boolean
  instagramMarketingProofUrl?: boolean
  twibbonLink?: boolean
  status?: boolean
  rejectionReason?: boolean
  reviewedByAdminId?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SubmissionVerificationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "krsScanUrl" | "formalPhotoUrl" | "instagramProofUrl" | "instagramMarketingProofUrl" | "twibbonLink" | "status" | "rejectionReason" | "reviewedByAdminId" | "reviewedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["submissionVerification"]>
export type SubmissionVerificationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}
export type SubmissionVerificationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}
export type SubmissionVerificationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedByAdmin?: boolean | Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>
}

export type $SubmissionVerificationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubmissionVerification"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    reviewedByAdmin: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    krsScanUrl: string | null
    formalPhotoUrl: string | null
    instagramProofUrl: string | null
    instagramMarketingProofUrl: string | null
    twibbonLink: string | null
    status: $Enums.VerificationStatus
    rejectionReason: string | null
    reviewedByAdminId: string | null
    reviewedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["submissionVerification"]>
  composites: {}
}

export type SubmissionVerificationGetPayload<S extends boolean | null | undefined | SubmissionVerificationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload, S>

export type SubmissionVerificationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubmissionVerificationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubmissionVerificationCountAggregateInputType | true
  }

export interface SubmissionVerificationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubmissionVerification'], meta: { name: 'SubmissionVerification' } }
  /**
   * Find zero or one SubmissionVerification that matches the filter.
   * @param {SubmissionVerificationFindUniqueArgs} args - Arguments to find a SubmissionVerification
   * @example
   * // Get one SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubmissionVerificationFindUniqueArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubmissionVerification that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubmissionVerificationFindUniqueOrThrowArgs} args - Arguments to find a SubmissionVerification
   * @example
   * // Get one SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubmissionVerificationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubmissionVerification that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationFindFirstArgs} args - Arguments to find a SubmissionVerification
   * @example
   * // Get one SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubmissionVerificationFindFirstArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubmissionVerification that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationFindFirstOrThrowArgs} args - Arguments to find a SubmissionVerification
   * @example
   * // Get one SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubmissionVerificationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubmissionVerifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubmissionVerifications
   * const submissionVerifications = await prisma.submissionVerification.findMany()
   * 
   * // Get first 10 SubmissionVerifications
   * const submissionVerifications = await prisma.submissionVerification.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const submissionVerificationWithIdOnly = await prisma.submissionVerification.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubmissionVerificationFindManyArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubmissionVerification.
   * @param {SubmissionVerificationCreateArgs} args - Arguments to create a SubmissionVerification.
   * @example
   * // Create one SubmissionVerification
   * const SubmissionVerification = await prisma.submissionVerification.create({
   *   data: {
   *     // ... data to create a SubmissionVerification
   *   }
   * })
   * 
   */
  create<T extends SubmissionVerificationCreateArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationCreateArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubmissionVerifications.
   * @param {SubmissionVerificationCreateManyArgs} args - Arguments to create many SubmissionVerifications.
   * @example
   * // Create many SubmissionVerifications
   * const submissionVerification = await prisma.submissionVerification.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubmissionVerificationCreateManyArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubmissionVerifications and returns the data saved in the database.
   * @param {SubmissionVerificationCreateManyAndReturnArgs} args - Arguments to create many SubmissionVerifications.
   * @example
   * // Create many SubmissionVerifications
   * const submissionVerification = await prisma.submissionVerification.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubmissionVerifications and only return the `id`
   * const submissionVerificationWithIdOnly = await prisma.submissionVerification.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubmissionVerificationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubmissionVerification.
   * @param {SubmissionVerificationDeleteArgs} args - Arguments to delete one SubmissionVerification.
   * @example
   * // Delete one SubmissionVerification
   * const SubmissionVerification = await prisma.submissionVerification.delete({
   *   where: {
   *     // ... filter to delete one SubmissionVerification
   *   }
   * })
   * 
   */
  delete<T extends SubmissionVerificationDeleteArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationDeleteArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubmissionVerification.
   * @param {SubmissionVerificationUpdateArgs} args - Arguments to update one SubmissionVerification.
   * @example
   * // Update one SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubmissionVerificationUpdateArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationUpdateArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubmissionVerifications.
   * @param {SubmissionVerificationDeleteManyArgs} args - Arguments to filter SubmissionVerifications to delete.
   * @example
   * // Delete a few SubmissionVerifications
   * const { count } = await prisma.submissionVerification.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubmissionVerificationDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubmissionVerificationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubmissionVerifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubmissionVerifications
   * const submissionVerification = await prisma.submissionVerification.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubmissionVerificationUpdateManyArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubmissionVerifications and returns the data updated in the database.
   * @param {SubmissionVerificationUpdateManyAndReturnArgs} args - Arguments to update many SubmissionVerifications.
   * @example
   * // Update many SubmissionVerifications
   * const submissionVerification = await prisma.submissionVerification.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubmissionVerifications and only return the `id`
   * const submissionVerificationWithIdOnly = await prisma.submissionVerification.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubmissionVerificationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubmissionVerification.
   * @param {SubmissionVerificationUpsertArgs} args - Arguments to update or create a SubmissionVerification.
   * @example
   * // Update or create a SubmissionVerification
   * const submissionVerification = await prisma.submissionVerification.upsert({
   *   create: {
   *     // ... data to create a SubmissionVerification
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubmissionVerification we want to update
   *   }
   * })
   */
  upsert<T extends SubmissionVerificationUpsertArgs>(args: Prisma.SelectSubset<T, SubmissionVerificationUpsertArgs<ExtArgs>>): Prisma.Prisma__SubmissionVerificationClient<runtime.Types.Result.GetResult<Prisma.$SubmissionVerificationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubmissionVerifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationCountArgs} args - Arguments to filter SubmissionVerifications to count.
   * @example
   * // Count the number of SubmissionVerifications
   * const count = await prisma.submissionVerification.count({
   *   where: {
   *     // ... the filter for the SubmissionVerifications we want to count
   *   }
   * })
  **/
  count<T extends SubmissionVerificationCountArgs>(
    args?: Prisma.Subset<T, SubmissionVerificationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubmissionVerificationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubmissionVerification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubmissionVerificationAggregateArgs>(args: Prisma.Subset<T, SubmissionVerificationAggregateArgs>): Prisma.PrismaPromise<GetSubmissionVerificationAggregateType<T>>

  /**
   * Group by SubmissionVerification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionVerificationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubmissionVerificationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubmissionVerificationGroupByArgs['orderBy'] }
      : { orderBy?: SubmissionVerificationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubmissionVerificationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubmissionVerificationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubmissionVerification model
 */
readonly fields: SubmissionVerificationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubmissionVerification.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubmissionVerificationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reviewedByAdmin<T extends Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubmissionVerification$reviewedByAdminArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubmissionVerification model
 */
export interface SubmissionVerificationFieldRefs {
  readonly id: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly userId: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly krsScanUrl: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly formalPhotoUrl: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly instagramProofUrl: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly instagramMarketingProofUrl: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly twibbonLink: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly status: Prisma.FieldRef<"SubmissionVerification", 'VerificationStatus'>
  readonly rejectionReason: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly reviewedByAdminId: Prisma.FieldRef<"SubmissionVerification", 'String'>
  readonly reviewedAt: Prisma.FieldRef<"SubmissionVerification", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"SubmissionVerification", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SubmissionVerification", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SubmissionVerification findUnique
 */
export type SubmissionVerificationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionVerification to fetch.
   */
  where: Prisma.SubmissionVerificationWhereUniqueInput
}

/**
 * SubmissionVerification findUniqueOrThrow
 */
export type SubmissionVerificationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionVerification to fetch.
   */
  where: Prisma.SubmissionVerificationWhereUniqueInput
}

/**
 * SubmissionVerification findFirst
 */
export type SubmissionVerificationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionVerification to fetch.
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionVerifications to fetch.
   */
  orderBy?: Prisma.SubmissionVerificationOrderByWithRelationInput | Prisma.SubmissionVerificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubmissionVerifications.
   */
  cursor?: Prisma.SubmissionVerificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionVerifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionVerifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubmissionVerifications.
   */
  distinct?: Prisma.SubmissionVerificationScalarFieldEnum | Prisma.SubmissionVerificationScalarFieldEnum[]
}

/**
 * SubmissionVerification findFirstOrThrow
 */
export type SubmissionVerificationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionVerification to fetch.
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionVerifications to fetch.
   */
  orderBy?: Prisma.SubmissionVerificationOrderByWithRelationInput | Prisma.SubmissionVerificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubmissionVerifications.
   */
  cursor?: Prisma.SubmissionVerificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionVerifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionVerifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubmissionVerifications.
   */
  distinct?: Prisma.SubmissionVerificationScalarFieldEnum | Prisma.SubmissionVerificationScalarFieldEnum[]
}

/**
 * SubmissionVerification findMany
 */
export type SubmissionVerificationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionVerifications to fetch.
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionVerifications to fetch.
   */
  orderBy?: Prisma.SubmissionVerificationOrderByWithRelationInput | Prisma.SubmissionVerificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubmissionVerifications.
   */
  cursor?: Prisma.SubmissionVerificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionVerifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionVerifications.
   */
  skip?: number
  distinct?: Prisma.SubmissionVerificationScalarFieldEnum | Prisma.SubmissionVerificationScalarFieldEnum[]
}

/**
 * SubmissionVerification create
 */
export type SubmissionVerificationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * The data needed to create a SubmissionVerification.
   */
  data: Prisma.XOR<Prisma.SubmissionVerificationCreateInput, Prisma.SubmissionVerificationUncheckedCreateInput>
}

/**
 * SubmissionVerification createMany
 */
export type SubmissionVerificationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubmissionVerifications.
   */
  data: Prisma.SubmissionVerificationCreateManyInput | Prisma.SubmissionVerificationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubmissionVerification createManyAndReturn
 */
export type SubmissionVerificationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * The data used to create many SubmissionVerifications.
   */
  data: Prisma.SubmissionVerificationCreateManyInput | Prisma.SubmissionVerificationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubmissionVerification update
 */
export type SubmissionVerificationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * The data needed to update a SubmissionVerification.
   */
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateInput, Prisma.SubmissionVerificationUncheckedUpdateInput>
  /**
   * Choose, which SubmissionVerification to update.
   */
  where: Prisma.SubmissionVerificationWhereUniqueInput
}

/**
 * SubmissionVerification updateMany
 */
export type SubmissionVerificationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubmissionVerifications.
   */
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateManyMutationInput, Prisma.SubmissionVerificationUncheckedUpdateManyInput>
  /**
   * Filter which SubmissionVerifications to update
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * Limit how many SubmissionVerifications to update.
   */
  limit?: number
}

/**
 * SubmissionVerification updateManyAndReturn
 */
export type SubmissionVerificationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * The data used to update SubmissionVerifications.
   */
  data: Prisma.XOR<Prisma.SubmissionVerificationUpdateManyMutationInput, Prisma.SubmissionVerificationUncheckedUpdateManyInput>
  /**
   * Filter which SubmissionVerifications to update
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * Limit how many SubmissionVerifications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubmissionVerification upsert
 */
export type SubmissionVerificationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * The filter to search for the SubmissionVerification to update in case it exists.
   */
  where: Prisma.SubmissionVerificationWhereUniqueInput
  /**
   * In case the SubmissionVerification found by the `where` argument doesn't exist, create a new SubmissionVerification with this data.
   */
  create: Prisma.XOR<Prisma.SubmissionVerificationCreateInput, Prisma.SubmissionVerificationUncheckedCreateInput>
  /**
   * In case the SubmissionVerification was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubmissionVerificationUpdateInput, Prisma.SubmissionVerificationUncheckedUpdateInput>
}

/**
 * SubmissionVerification delete
 */
export type SubmissionVerificationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
  /**
   * Filter which SubmissionVerification to delete.
   */
  where: Prisma.SubmissionVerificationWhereUniqueInput
}

/**
 * SubmissionVerification deleteMany
 */
export type SubmissionVerificationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubmissionVerifications to delete
   */
  where?: Prisma.SubmissionVerificationWhereInput
  /**
   * Limit how many SubmissionVerifications to delete.
   */
  limit?: number
}

/**
 * SubmissionVerification.reviewedByAdmin
 */
export type SubmissionVerification$reviewedByAdminArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * SubmissionVerification without action
 */
export type SubmissionVerificationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionVerification
   */
  select?: Prisma.SubmissionVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionVerification
   */
  omit?: Prisma.SubmissionVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionVerificationInclude<ExtArgs> | null
}
